import { GoogleGenAI } from "@google/genai";
import type { IProcessWorker, WorkerEvent } from "./worker-interface.ts";
import * as fs from "node:fs";
import * as path from "node:path";
import * as os from "node:os";
import { execSync } from "node:child_process";
import { getSchema, toCamelCase, jsonElementToWikiPage, transitionTarget, type WikiPage } from "./wiki.ts";
import { checkElement, checkProvenance, checkFrontmatter, checkFieldValues, checkConformance } from "./conformance.ts";
import { updateElement } from "./wiki-write.ts";


const SESSION_MODEL = process.env.SESSION_MODEL || "gemini-2.5-pro";

// All 21 dynamic skills in the Processminer roster
const SKILL_NAMES = [
  "add-entry",
  "area-summary",
  "client-journey-specialist",
  "comment-review",
  "conflict-resolution",
  "control-compliance-specialist",
  "council-review",
  "document-ingest",
  "dogfood-run",
  "foundational-run",
  "innovation-analyst",
  "it-architect",
  "new-process",
  "process-specialist",
  "qer-session",
  "run-lint",
  "source-cx",
  "source-innovation",
  "source-regulation",
  "source-target",
  "transformation-agent"
];

// Declarations of local tools available to the Gemini agent
const toolDeclarations: any[] = [
  {
    name: "expandElement",
    description: "Expand an abridged collection list or retrieve the full content of a specific element.",
    parameters: {
      type: "OBJECT",
      properties: {
        type: { type: "STRING", description: "The collection name, e.g. 'process-steps', 'exceptions', 'pain-points', 'roles', 'metrics'." },
        id: { type: "STRING", description: "Optional. The specific element ID to expand (e.g. 'PS-COB-001'). If omitted, returns all element IDs and titles in the collection." }
      },
      required: ["type"]
    }
  },
  {
    name: "createElement",
    description: "Create a new process element conforming to the JSON schema. The ID is automatically generated by the backend.",
    parameters: {
      type: "OBJECT",
      properties: {
        type: { type: "STRING", description: "The collection name, e.g. 'process-steps', 'exceptions', 'pain-points', 'roles', 'metrics'." },
        tempKey: { type: "STRING", description: "Optional. An ephemeral temporary key used to reference this element in other parallel tool calls during the same turn." },
        element: {
          type: "OBJECT",
          description: "The element payload containing metadata (meta) and content fields, conforming to the JSON schema. Do not include 'id' inside meta; it is auto-assigned.",
          properties: {
            meta: {
              type: "OBJECT",
              description: "Metadata fields (status, confidence, source, provenance, owner, etc.)",
              properties: {
                status: { type: "STRING", description: "Defaults to 'draft'." },
                confidence: { type: "STRING", description: "high, medium, or low" },
                source: { type: "STRING", description: "Verification source" },
                provenance: {
                  type: "OBJECT",
                  description: "Provenance mapping for each template heading block, e.g. { 'What happens': { source: 'elicited', evidence: 'quote' } }"
                }
              },
              required: ["source"]
            },
            content: {
              type: "OBJECT",
              description: "The domain-specific fields and blocks (title, description, inputs, outputs, etc.)"
            }
          },
          required: ["meta", "content"]
        }
      },
      required: ["type", "element"]
    }
  },
  {
    name: "updateElement",
    description: "Update an existing process element by applying a deep merge patch.",
    parameters: {
      type: "OBJECT",
      properties: {
        id: { type: "STRING", description: "The unique ID of the element to update (e.g. 'PS-COB-001')." },
        patch: {
          type: "OBJECT",
          description: "JSON object containing updated fields in meta and/or content to merge into the element.",
          properties: {
            meta: { type: "OBJECT", description: "Metadata fields to update" },
            content: { type: "OBJECT", description: "Content fields to update" }
          }
        }
      },
      required: ["id", "patch"]
    }
  },
  {
    name: "checkConformance",
    description: "Run deterministic template-conformance checks on all elements in the process.",
    parameters: {
      type: "OBJECT",
      properties: {
        slug: { type: "STRING", description: "The process slug." }
      },
      required: ["slug"]
    }
  },
  {
    name: "checkTransitions",
    description: "Reconcile process-step transitions against exceptions to find orphans or broken links.",
    parameters: {
      type: "OBJECT",
      properties: {
        slug: { type: "STRING", description: "The process slug." }
      },
      required: ["slug"]
    }
  },
  {
    name: "applyLint",
    description: "Apply a set of lint findings: writes findings to the process JSON and reopens any implicated approved elements.",
    parameters: {
      type: "OBJECT",
      properties: {
        slug: { type: "STRING", description: "The process slug." },
        findings: {
          type: "ARRAY",
          description: "List of findings to write.",
          items: {
            type: "OBJECT",
            properties: {
              kind: { type: "STRING", description: "conformance, discrepancy, or question" },
              title: { type: "STRING", description: "Finding headline" },
              detail: { type: "STRING", description: "Detailed description or question" },
              elements: {
                type: "ARRAY",
                items: { type: "STRING" },
                description: "List of implicated element IDs"
              }
            },
            required: ["kind", "title", "detail", "elements"]
          }
        }
      },
      required: ["slug", "findings"]
    }
  }
];

export function replaceTempKeys(obj: any, tempKeyMap: Map<string, string>): any {
  if (typeof obj === "string") {
    if (obj.startsWith("@")) {
      const key = obj.slice(1);
      if (tempKeyMap.has(key)) {
        return tempKeyMap.get(key);
      }
    }
    return obj;
  }
  if (Array.isArray(obj)) {
    return obj.map(item => replaceTempKeys(item, tempKeyMap));
  }
  if (typeof obj === "object" && obj !== null) {
    const res: any = {};
    for (const [k, v] of Object.entries(obj)) {
      res[k] = replaceTempKeys(v, tempKeyMap);
    }
    return res;
  }
  return obj;
}

// SESSIONS_MAP_PATH tracks process slugs across session IDs
const SESSIONS_MAP_PATH = path.join(process.cwd(), "wiki", "processes", ".sessions.json");

function saveSessionSlug(sessionId: string, slug: string, activeSkill: string | null = null) {
  try {
    const dir = path.dirname(SESSIONS_MAP_PATH);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    const data = fs.existsSync(SESSIONS_MAP_PATH) ? JSON.parse(fs.readFileSync(SESSIONS_MAP_PATH, "utf8")) : {};
    data[sessionId] = { slug, activeSkill };
    fs.writeFileSync(SESSIONS_MAP_PATH, JSON.stringify(data, null, 2), "utf8");
  } catch (e) {
    console.error("Failed to save session slug map:", e);
  }
}

function appendToCentralLog(sessionId: string, slug: string | undefined, role: "User" | "Model" | "System" | "Error", text: string) {
  try {
    const logDir = path.join(process.cwd(), "logs");
    if (!fs.existsSync(logDir)) {
      fs.mkdirSync(logDir, { recursive: true });
    }
    const logPath = path.join(logDir, "assistant.log");
    const ts = new Date().toISOString();
    const sessionPart = sessionId.slice(0, 8);
    const slugPart = slug ? ` [${slug}]` : "";
    const logLine = `[${ts}] [${sessionPart}]${slugPart} [${role}] ${text}\n`;
    fs.appendFileSync(logPath, logLine, "utf8");
  } catch (err) {
    console.error("Failed to append to central log:", err);
  }
}

function getSessionInfo(sessionId: string): { slug: string | null; activeSkill: string | null } {
  try {
    if (!fs.existsSync(SESSIONS_MAP_PATH)) return { slug: null, activeSkill: null };
    const data = JSON.parse(fs.readFileSync(SESSIONS_MAP_PATH, "utf8"));
    const entry = data[sessionId];
    if (typeof entry === "string") {
      return { slug: entry, activeSkill: null };
    } else if (entry && typeof entry === "object") {
      return { slug: entry.slug || null, activeSkill: entry.activeSkill || null };
    }
    return { slug: null, activeSkill: null };
  } catch (e) {
    console.error("Failed to read session slug map:", e);
    return { slug: null, activeSkill: null };
  }
}

function generateDocumentMap(doc: any, activeCollection: string | null = null, activeElementId: string | null = null): any {
  const result: any = { meta: doc.meta, content: doc.content }; 
  const schemaReferences: Record<string, string[]> = {
    "process-step": ["roles", "systems"], 
    "system": ["integrations", "roles"],
    "role": ["systems", "controls"]
  };
  
  const activeElement = activeCollection && activeElementId 
    ? doc[activeCollection]?.find((el: any) => el.meta?.id === activeElementId)
    : null;
  const referencedCollections = activeElement ? (schemaReferences[activeElement.meta?.type] || []) : [];
  
  Object.keys(doc).forEach(key => {
    if (!Array.isArray(doc[key])) return;
    
    if (activeCollection && key === activeCollection) {
      result[key] = doc[key].map((el: any) => {
        if (el.meta?.id === activeElementId) {
          return el; // full-expand
        } else {
          return { meta: { id: el.meta?.id }, content: { title: el.content?.title } }; // list peers
        }
      });
    } 
    else if (referencedCollections.includes(key)) {
      result[key] = doc[key].map((el: any) => {
        return { meta: { id: el.meta?.id }, content: { title: el.content?.title } };
      });
    } 
    else {
      // Default: list process steps at a high level if no element is active
      if (!activeElementId && key === "process-steps") {
        result[key] = doc[key].map((el: any) => {
          return { meta: { id: el.meta?.id }, content: { title: el.content?.title } };
        });
      } else {
        result[key] = doc[key].length;
      }
    }
  });
  
  return result;
}

function customStringify(obj: any, indent = ""): string {
  if (Array.isArray(obj)) {
    if (obj.length === 0) return "[]";
    let out = "[\n";
    for (let i = 0; i < obj.length; i++) {
      let isLast = i === obj.length - 1;
      const isListItem = obj[i] && obj[i].meta && obj[i].meta.id && Object.keys(obj[i]).length === 2 && obj[i].content && obj[i].content.title;
      
      if (isListItem) {
        out += `${indent}  { "meta": { "id": "${obj[i].meta.id}" /*...*/ }, "content": { "title": "${obj[i].content.title}" /*...*/ } }${isLast ? "" : ","}\n`;
      } else {
        const lines = JSON.stringify(obj[i], null, 2).split('\n');
        out += lines.map((l, idx) => (idx === 0 ? indent + "  " + l : indent + "  " + l)).join('\n') + (isLast ? "" : ",") + "\n";
      }
    }
    out += indent + "]";
    return out;
  }
  
  if (typeof obj === "object" && obj !== null) {
    let out = "{\n";
    const keys = Object.keys(obj);
    for (let i = 0; i < keys.length; i++) {
      const k = keys[i];
      let isLast = i === keys.length - 1;
      if (typeof obj[k] === "number") {
         out += `${indent}  "${k}": ${obj[k]} /*...*/${isLast ? "" : ","}\n`;
      } else if (Array.isArray(obj[k])) {
         out += `${indent}  "${k}": ${customStringify(obj[k], indent + "  ")}${isLast ? "" : ","}\n`;
      } else {
         out += `${indent}  "${k}": ${JSON.stringify(obj[k], null, 2).replace(/\n/g, '\n' + indent + '  ')}${isLast ? "" : ","}\n`;
      }
    }
    out += indent + "}";
    return out;
  }
  return JSON.stringify(obj);
}

export function generateNextId(data: any, elementType: string, idPrefix: string): string {
  let procAbbrev = "";
  let maxSeq = 0;

  for (const [key, val] of Object.entries(data)) {
    if (!Array.isArray(val)) continue;
    for (const el of val) {
      const elId = el.meta?.id;
      if (typeof elId === "string") {
        const parts = elId.split("-");
        if (parts.length === 3) {
          if (!procAbbrev) {
            procAbbrev = parts[1];
          }
          if (el.meta?.type === elementType && /^\d+$/.test(parts[2])) {
            const seq = parseInt(parts[2], 10);
            if (seq > maxSeq) {
              maxSeq = seq;
            }
          }
        }
      }
    }
  }

  if (!procAbbrev) {
    const procId = data.meta?.id || "";
    procAbbrev = procId.split("-")[0] || "PROC";
  }

  const nextSeq = maxSeq + 1;
  const nextSeqStr = String(nextSeq).padStart(3, "0");
  return `${idPrefix}-${procAbbrev}-${nextSeqStr}`;
}

export class GeminiWorker implements IProcessWorker {
  readonly id = crypto.randomUUID();
  sessionId: string | null = null;
  busy = false;
  lastUsed = Date.now();
  alive = true;
  private slug: string | undefined;
  private activeSkill: string | null = null;

  private ai: GoogleGenAI;
  private history: Array<any> = [];

  constructor(resumeId?: string | null) {
    this.sessionId = resumeId || crypto.randomUUID();
    this.ai = new GoogleGenAI({
      apiKey: process.env.GEMINI_API_KEY || undefined,
    });
    if (this.sessionId) {
      const info = getSessionInfo(this.sessionId);
      this.slug = info.slug || undefined;
      this.activeSkill = info.activeSkill || null;
    }
  }

  private buildSystemInstruction(message: string): string {
    let instruction = "";

    // 1. Prepend CORE_SYSTEM_PROMPT.md if available
    const corePromptPath = path.join(process.cwd(), ".claude", "skills", "CORE_SYSTEM_PROMPT.md");
    if (fs.existsSync(corePromptPath)) {
      try {
        instruction += fs.readFileSync(corePromptPath, "utf8") + "\n\n";
      } catch (e) {
        console.error("Failed to read CORE_SYSTEM_PROMPT.md:", e);
      }
    } else {
      instruction += "You are Processminer, an AI-native process documentation assistant.\n\n";
    }

    // 2. Append Core Process Schema
    const schemaPath = path.join(process.cwd(), "schema", "process-schema.json");
    if (fs.existsSync(schemaPath)) {
      try {
        const schema = fs.readFileSync(schemaPath, "utf8");
        instruction += `### Core Process Schema:\nUse this schema as your single source of truth for element types, sections, frontmatter fields, and relations:\n${schema}\n\n`;
      } catch {
        /* fallback */
      }
    }

    // 3. Dynamic Skill Elicitation: Scan for any of the 21 skill names
    let activeSkill: string | null = this.activeSkill;
    const msgLower = message.toLowerCase();

    let foundSkill: string | null = null;
    for (const skill of SKILL_NAMES) {
      // If we are in a scoped session (this.slug is set), ignore "new-process" since it's only for unscoped creation.
      if (this.slug && skill === "new-process") {
        continue;
      }
      if (msgLower.includes(skill) || msgLower.includes(skill.replace("-", " "))) {
        foundSkill = skill;
        break;
      }
    }

    if (foundSkill) {
      activeSkill = foundSkill;
    } else if (!activeSkill) {
      if (msgLower.includes("lint")) activeSkill = "run-lint";
      else if (msgLower.includes("ingest")) activeSkill = "document-ingest";
      else if (!this.slug && msgLower.includes("new-process")) activeSkill = "new-process";
      else if (msgLower.includes("foundational")) activeSkill = "foundational-run";
      else if (msgLower.includes("conflict")) activeSkill = "conflict-resolution";
      
      // Default to process-specialist if it mentions steps/process or is a general documentation request,
      // or if we are in a scoped session.
      if (!activeSkill && (this.slug || msgLower.includes("step") || msgLower.includes("process") || msgLower.includes("document"))) {
        activeSkill = "process-specialist";
      }
    }

    // Force process-specialist if we are in a scoped session and activeSkill is new-process or not set
    if (this.slug && (activeSkill === "new-process" || !activeSkill)) {
      activeSkill = "process-specialist";
    }

    this.activeSkill = activeSkill;
    if (this.sessionId && this.slug && this.activeSkill) {
      saveSessionSlug(this.sessionId, this.slug, this.activeSkill);
    }

    if (activeSkill) {
      const skillPath = path.join(process.cwd(), ".claude", "skills", activeSkill, "SKILL.md");
      if (fs.existsSync(skillPath)) {
        try {
          const skillInstruction = fs.readFileSync(skillPath, "utf8");
          instruction += `### Active Specialist Guidelines (${activeSkill}):\nFollow these procedures strictly:\n${skillInstruction}\n\n`;
        } catch {
          /* fallback */
        }
      }
    }

    // 4. Dynamically append the abridged JSON Document Map context
    if (this.slug) {
      const processFilePath = path.join(process.cwd(), "wiki", "processes", `${this.slug}.json`);
      if (fs.existsSync(processFilePath)) {
        try {
          const doc = JSON.parse(fs.readFileSync(processFilePath, "utf8"));
          let activeCollection = null;
          let activeId = null;
          // Attempt to read from qer-state.json
          const qerStatePath = path.join(process.cwd(), "wiki", "processes", this.slug, "qer-state.json");
          if (fs.existsSync(qerStatePath)) {
            const qerState = JSON.parse(fs.readFileSync(qerStatePath, "utf8"));
            activeCollection = qerState.section;
            activeId = qerState.id;
          }
          const docMap = generateDocumentMap(doc, activeCollection, activeId);
          instruction += `### Current Document Map:\nThis is the current state of the document you are authoring:\n${customStringify(docMap)}\n\n`;
        } catch (e) {
          console.error("Failed to build Document Map in system instructions:", e);
        }
      }
    }

    return instruction;
  }

  async *runTurn(message: string, skill?: string | null): AsyncGenerator<WorkerEvent> {
    if (!this.alive) {
      throw new Error("This assistant session is no longer running.");
    }
    if (this.busy) {
      throw new Error("This assistant session is already handling a turn.");
    }
    this.busy = true;
    this.lastUsed = Date.now();

    if (skill) {
      this.activeSkill = skill;
    }

    // Extract process slug from scope preamble if present, or rehydrate from sessions map
    if (this.sessionId) {
      const match = message.match(/wiki\/processes\/([^/]+)\//);
      if (match) {
        this.slug = match[1];
        saveSessionSlug(this.sessionId, this.slug, this.activeSkill);
      } else if (!this.slug) {
        const info = getSessionInfo(this.sessionId);
        this.slug = info.slug || undefined;
        if (!this.activeSkill) {
          this.activeSkill = info.activeSkill || null;
        }
      }
    }

    try {
      const systemInstruction = this.buildSystemInstruction(message);

      this.history.push({
        role: "user",
        parts: [{ text: message }],
      });

      let loopActive = true;
      let turns = 0;
      const MAX_TURNS = 35; // Loop cap to prevent infinity recursion

      const activeTools = toolDeclarations;

      appendToCentralLog(this.sessionId || "unknown", this.slug, "User", `Message:\n${message}`);
      appendToCentralLog(this.sessionId || "unknown", this.slug, "System", `Skill: ${this.activeSkill} | Active Tools: ${activeTools.map(t => t.name).join(", ")}`);

      while (loopActive && turns < MAX_TURNS) {
        if (!this.alive) {
          break;
        }
        turns++;

        // Request content generation (with native tool definitions)
        const response = await this.ai.models.generateContent({
          model: SESSION_MODEL,
          contents: this.history,
          config: {
            systemInstruction,
            tools: [{ functionDeclarations: activeTools }]
          }
        });

        const calls = response.functionCalls;

        if (calls && calls.length > 0) {
          console.log("[gemini-worker] Raw parts from API:", JSON.stringify(response.candidates?.[0]?.content?.parts, null, 2));
          calls.forEach((c) => {
            appendToCentralLog(this.sessionId || "unknown", this.slug, "Model", `Tool Call: ${c.name}(\n${JSON.stringify(c.args, null, 2)}\n)`);
          });
          // 1. Yield tool use events to update the client's progress UI
          yield {
            type: "assistant",
            message: {
              content: calls.map((c, idx) => ({
                type: "tool_use",
                name: c.name,
                input: c.args as Record<string, unknown>,
                id: `call_${turns}_${idx}`
              }))
            }
          };

          const candidateParts = response.candidates?.[0]?.content?.parts || [];
          const functionCallParts = candidateParts.filter((p: any) => p.functionCall);

          // 2. Iterate and execute requested tools locally in sequence (sequential singleton pattern)
          const tempKeyMap = new Map<string, string>();
          const schema = getSchema();
          
          let doc: any = null;
          let processFilePath = "";
          if (this.slug) {
            processFilePath = path.join(process.cwd(), "wiki", "processes", `${this.slug}.json`);
            if (fs.existsSync(processFilePath)) {
              try {
                doc = JSON.parse(fs.readFileSync(processFilePath, "utf8"));
              } catch (e: any) {
                console.error("Failed to parse process json:", e);
              }
            }
          }

          const userParts: any[] = [];

          for (let idx = 0; idx < calls.length; idx++) {
            // Reload doc from disk to get the latest state after any writes
            if (this.slug && fs.existsSync(processFilePath)) {
              try {
                doc = JSON.parse(fs.readFileSync(processFilePath, "utf8"));
              } catch (e: any) {
                console.error("Failed to parse process json inside loop:", e);
              }
            }

            const call = calls[idx];
            const originalName = functionCallParts[idx]?.functionCall?.name || call.name || "";
            const isExpandElement = originalName === "expandElement";
            const isCreateElement = originalName === "createElement";
            const isUpdateElement = originalName === "updateElement";

            let resultText = "";
            try {
              console.log(`[gemini-worker] Executing tool sequentially: ${originalName}`, call.args);
              const args = (call.args || {}) as any;

              if (isExpandElement) {
                const type = args.type;
                const id = args.id;
                if (!doc) {
                  throw new Error("Process document context not loaded or slug is missing.");
                }
                if (!id) {
                  const list = doc[type] || [];
                  const elements = list.map((el: any) => ({
                    id: el.meta?.id,
                    title: el.content?.title
                  }));
                  resultText = JSON.stringify({ type, elements }, null, 2);
                } else {
                  const list = doc[type] || [];
                  const element = list.find((el: any) => el.meta?.id === id);
                  if (!element) {
                    throw new Error(`Element ${id} not found in collection ${type}.`);
                  }
                  resultText = JSON.stringify(element, null, 2);
                }
              } else if (isCreateElement) {
                const type = args.type;
                let element = args.element;
                const tempKey = args.tempKey;

                if (!doc) {
                  throw new Error("Process document context not loaded or slug is missing.");
                }

                // Resolve tempKey references
                element = replaceTempKeys(element, tempKeyMap);

                let singularType = "";
                for (const [t, def] of Object.entries(schema.elementTypes)) {
                  if (def.section === type) {
                    singularType = t;
                    break;
                  }
                }
                if (!singularType) {
                  throw new Error(`Unknown collection type: ${type}`);
                }
                const info = schema.elementTypes[singularType];
                const idPrefix = info.idPrefix;
                const newId = generateNextId(doc, singularType, idPrefix);

                const newMeta = {
                  ...(element.meta || {}),
                  id: newId,
                  type: singularType,
                  section: type,
                  status: element.meta?.status || "draft",
                };
                const newContent = {
                  ...(element.content || {})
                };
                const fullElement = { meta: newMeta, content: newContent };

                const pageRepresentation = jsonElementToWikiPage(fullElement, info);
                const validationIssues = [
                  ...checkElement(pageRepresentation, info.template || []).filter(c => !c.ok).map(c => `“${c.heading}” ${c.issue}`),
                  ...checkFrontmatter(pageRepresentation, info),
                  ...checkFieldValues(pageRepresentation, info, schema),
                  ...checkProvenance(pageRepresentation, info)
                ];

                if (validationIssues.length > 0) {
                  resultText = `Error: Element validation failed:\n- ${validationIssues.join("\n- ")}`;
                } else {
                  if (!doc[type]) doc[type] = [];
                  doc[type].push(fullElement);
                  if (singularType === "process-step") {
                    doc[type].sort((a: any, b: any) => (a.meta?.sequence || 999) - (b.meta?.sequence || 999));
                  }

                  // Write directly to disk immediately
                  fs.writeFileSync(processFilePath, JSON.stringify(doc, null, 2) + "\n", "utf8");

                  if (tempKey) {
                    const cleanKey = tempKey.startsWith("@") ? tempKey.slice(1) : tempKey;
                    tempKeyMap.set(cleanKey, newId);
                  }

                  resultText = JSON.stringify({ ok: true, id: newId, element: fullElement }, null, 2);
                }
              } else if (isUpdateElement) {
                const id = args.id;
                let patch = args.patch || {};

                if (!doc) {
                  throw new Error("Process document context not loaded or slug is missing.");
                }

                // Resolve tempKey in patch payload
                patch = replaceTempKeys(patch, tempKeyMap);

                // Resolve target ID if it's a tempKey reference
                let targetId = id;
                if (targetId.startsWith("@")) {
                  const key = targetId.slice(1);
                  if (tempKeyMap.has(key)) {
                    targetId = tempKeyMap.get(key)!;
                  }
                }

                // Call the unified updateElement helper function which validates and writes directly to disk
                const res = await updateElement(this.slug!, targetId, patch);
                if (!res.ok) {
                  resultText = `Error: Element validation failed:\n- ${res.error}`;
                } else {
                  resultText = JSON.stringify({ ok: true, id: targetId, element: res.element }, null, 2);
                }
              } else if (originalName === "checkConformance") {
                if (!doc) {
                  throw new Error("Process document context not loaded or slug is missing.");
                }
                const elements: any[] = [];
                for (const [key, val] of Object.entries(doc)) {
                  if (!Array.isArray(val)) continue;
                  
                  let singularType = "";
                  for (const [t, def] of Object.entries(schema.elementTypes)) {
                    if ((def as any).section === key) {
                      singularType = t;
                      break;
                    }
                  }
                  if (!singularType) continue;
                  const info = schema.elementTypes[singularType];
                  
                  for (const el of val) {
                    const page = jsonElementToWikiPage(el, info);
                    elements.push(page);
                  }
                }
                const findings = checkConformance(elements, schema);
                resultText = JSON.stringify(findings, null, 2);
              } else if (originalName === "checkTransitions") {
                if (!doc) {
                  throw new Error("Process document context not loaded or slug is missing.");
                }
                const findings: any[] = [];
                const steps = doc["process-steps"] || [];
                const exceptions = doc["exceptions"] || [];
                
                const exceptionIds = new Set(exceptions.map((e: any) => e.meta?.id).filter(Boolean));
                const stepIds = new Set(steps.map((s: any) => s.meta?.id).filter(Boolean));
                const targetedExceptions = new Set<string>();
                
                let n = 0;
                for (const step of steps) {
                  const transitions = step.content?.transitions || [];
                  for (const t of transitions) {
                    const targetId = transitionTarget(t); // R7: accepts object or string form
                    if (targetId) {
                      if (targetId.startsWith("EX-")) {
                        targetedExceptions.add(targetId);
                        if (!exceptionIds.has(targetId)) {
                          n++;
                          findings.push({
                            id: `T-${n}`,
                            kind: "discrepancy",
                            title: `${step.content?.title || step.meta?.id} (${step.meta?.id})`,
                            detail: `Transitions to exception ${targetId} which does not exist in the document.`,
                            elements: [step.meta?.id]
                          });
                        }
                      }
                    }
                  }
                }
                
                for (const ex of exceptions) {
                  const exId = ex.meta?.id;
                  if (exId && !targetedExceptions.has(exId)) {
                    n++;
                    findings.push({
                      id: `T-${n}`,
                      kind: "discrepancy",
                      title: `${ex.content?.title || exId} (${exId})`,
                      detail: `Orphan exception — no process-step transition leads to this exception.`,
                      elements: [exId]
                    });
                  }
                }
                resultText = JSON.stringify(findings, null, 2);
              } else if (originalName === "applyLint") {
                const findings = args.findings || [];
                if (!doc) {
                  throw new Error("Process document context not loaded or slug is missing.");
                }
                
                const enrichedFindings = findings.map((f: any, i: number) => ({
                  ...f,
                  id: `F-${i + 1}`
                }));

                const lintReport = {
                  generatedAt: new Date().toISOString(),
                  slug: this.slug,
                  summary: {
                    conformance: enrichedFindings.filter((f: any) => f.kind === "conformance").length,
                    discrepancy: enrichedFindings.filter((f: any) => f.kind === "discrepancy").length,
                    question: enrichedFindings.filter((f: any) => f.kind === "question").length
                  },
                  findings: enrichedFindings,
                  reopens: [] as string[]
                };

                const reopens: string[] = [];
                for (const finding of enrichedFindings) {
                  if (Array.isArray(finding.elements)) {
                    for (const elId of finding.elements) {
                      for (const [key, val] of Object.entries(doc)) {
                        if (!Array.isArray(val)) continue;
                        const idx = val.findIndex((el: any) => el.meta?.id === elId);
                        if (idx !== -1) {
                          const el = val[idx];
                          if (el.meta?.approval === "approved") {
                            el.meta.approval = "in-progress";
                            el.meta.approvalBy = "run-lint";
                            el.meta.approvalDate = new Date().toISOString().slice(0, 10);
                            if (!reopens.includes(elId)) {
                              reopens.push(elId);
                            }
                          }
                        }
                      }
                    }
                  }
                }
                lintReport.reopens = reopens;
                doc.lint = lintReport;
                
                // Write directly to disk immediately
                fs.writeFileSync(processFilePath, JSON.stringify(doc, null, 2) + "\n", "utf8");

                resultText = JSON.stringify({
                  ok: true,
                  findingsCount: enrichedFindings.length,
                  reopenedCount: reopens.length,
                  summary: lintReport.summary
                }, null, 2);
              } else {
                throw new Error(`Unsupported tool: ${originalName}`);
              }
            } catch (err: any) {
              console.error(`[gemini-worker] Tool execution failed: ${originalName}`, err);
              resultText = `Error executing tool: ${err.message}`;
            }

            const hasError = resultText.startsWith("Error:") || resultText.startsWith("Error executing tool:");
            appendToCentralLog(
              this.sessionId || "unknown",
              this.slug,
              hasError ? "Error" : "System",
              `Tool Response (${originalName}):\n${resultText}`
            );

            userParts.push({
              functionResponse: {
                name: originalName,
                response: { result: resultText },
                id: functionCallParts[idx]?.functionCall?.id || (call as any).id
              }
            });
          }

          // 3. Yield tool resolutions to complete the UI chips
          yield {
            type: "user",
            message: {
              content: calls.map((c, idx) => ({
                type: "tool_result",
                tool_use_id: `call_${turns}_${idx}`
              }))
            }
          };

          // 4. Record tool calls and responses into conversation history, then loop back
          const modelParts = response.candidates?.[0]?.content?.parts || calls.map(c => ({ functionCall: c }));
          this.history.push({ role: "model", parts: modelParts });
          this.history.push({ role: "user", parts: userParts });

        } else {
          // No more function calls: this is the final answer
          const text = response.text || "";

          this.history.push({
            role: "model",
            parts: [{ text }],
          });

          appendToCentralLog(this.sessionId || "unknown", this.slug, "Model", `Reply:\n${text}`);

          // Yield stream_event deltas so the client prints the text smoothly
          yield {
            type: "stream_event",
            event: {
              type: "content_block_delta",
              delta: {
                type: "text_delta",
                text: text,
              },
            },
          };

          // Yield the final result
          yield {
            type: "result",
            result: text,
            session_id: this.sessionId,
          };

          // Save history log to a debug file in the process directory
          if (this.slug && this.sessionId) {
            try {
              const debugDir = path.join(process.cwd(), "wiki", "processes", this.slug);
              if (!fs.existsSync(debugDir)) fs.mkdirSync(debugDir, { recursive: true });
              const debugFilePath = path.join(debugDir, `session-${this.sessionId}.debug.json`);
              
              // Clean history of thought signatures
              const cleanHistory = this.history.map(turn => {
                if (!turn || !Array.isArray(turn.parts)) return turn;
                return {
                  ...turn,
                  parts: turn.parts.map((p: any) => {
                    const copy = { ...p };
                    delete copy.thoughtSignature;
                    return copy;
                  })
                };
              });

              fs.writeFileSync(debugFilePath, JSON.stringify({
                activeSkill: this.activeSkill,
                activeTools: activeTools.map(t => ({ name: t.name, description: t.description, parameters: t.parameters })),
                systemInstruction,
                history: cleanHistory,
              }, null, 2), "utf8");
            } catch (err) {
              console.error("Failed to write session debug file:", err);
            }
          }

          loopActive = false;
        }
      }

      if (loopActive) {
        throw new Error(`The assistant exceeded the maximum allowed research turns (${MAX_TURNS}) for a single response.`);
      }
    } catch (e: any) {
      console.error("[gemini-worker] Error in runTurn:", e);
      appendToCentralLog(this.sessionId || "unknown", this.slug, "Error", `Turn Failure: ${e.message}`);
      yield {
        type: "error",
        error: e instanceof Error ? e.message : "The Gemini assistant turn failed.",
        session_id: this.sessionId,
      };
    } finally {
      this.busy = false;
      this.lastUsed = Date.now();
    }
  }

  dispose(): void {
    this.alive = false;
    this.history = [];
  }
}
