import { GoogleGenAI } from "@google/genai";
import type { IProcessWorker, WorkerEvent } from "./worker-interface.ts";
import * as fs from "node:fs";
import { atomicWriteFileSync } from "./atomic-write.ts";
import * as path from "node:path";
import * as os from "node:os";
import { execSync } from "node:child_process";
import { getSchema, toCamelCase, jsonElementToWikiPage, transitionTarget, listProcesses, getProcessSummary, getProcessElements, searchProcesses, type WikiPage } from "./wiki.ts";
import { canAccess } from "./process-access.ts";
import { writeRuntime, getRuntime, setDtpSummary } from "./runtime-store.ts";
import { buildTargetReview, parseSummaryParts, buildIngestReport, clearIngestConflicts, buildApprovalPatch } from "./session-writes.ts";
import { writeDtpReport, writeDtpComparison } from "./dtp-report.ts";
import { buildNote, appendNote, resolveNotesInDoc } from "./session-notes.ts";
import {
  buildFoundationalQueue,
  newReviewState,
  advance,
  foundationalStatus,
  qerStatus,
  QER_STEPS,
} from "./session-cursor.ts";
import { checkConformance } from "./conformance.ts";
import { updateElement } from "./wiki-write.ts";
import {
  replaceTempKeys,
  generateNextId,
  buildElement,
  applyElement,
  createElementsBatch,
  type BatchSpec,
} from "./session-create.ts";

// The pure id/tempKey helpers moved to ./session-create.ts; re-export them from
// here so existing importers (claude-mcp-server, session-worker, lint.test) keep
// working unchanged.
export { replaceTempKeys, generateNextId } from "./session-create.ts";


const SESSION_MODEL = process.env.SESSION_MODEL || "gemini-2.5-pro";

// All 21 dynamic skills in the Processminer roster
const SKILL_NAMES = [
  "add-entry",
  "area-summary",
  "client-journey-specialist",
  "comment-review",
  "conflict-resolution",
  "control-compliance-specialist",
  "council-review",
  "document-ingest",
  "dogfood-run",
  "dtp-regenerate",
  "foundational-run",
  "innovation-analyst",
  "it-architect",
  "new-process",
  "process-specialist",
  "qer-session",
  "run-lint",
  "source-cx",
  "source-innovation",
  "source-regulation",
  "source-target",
  "transformation-agent"
];

// Declarations of local tools available to the Gemini agent
const toolDeclarations: any[] = [
  {
    name: "expandElement",
    description: "Expand an abridged collection list or retrieve the full content of a specific element.",
    parameters: {
      type: "OBJECT",
      properties: {
        type: { type: "STRING", description: "The collection name, e.g. 'process-steps', 'exceptions', 'pain-points', 'roles', 'metrics'." },
        id: { type: "STRING", description: "Optional. The specific element ID to expand (e.g. 'PS-COB-001'). If omitted, returns all element IDs and titles in the collection." }
      },
      required: ["type"]
    }
  },
  // ---- Advisory Board: read-only cross-process tools ----
  {
    name: "listAccessibleProcesses",
    description: "ADVISORY BOARD (read-only). List the processes available to advise on — {slug,title} for each. Takes no arguments.",
    parameters: { type: "OBJECT", properties: {} }
  },
  {
    name: "getProcessSummary",
    description: "ADVISORY BOARD (read-only). A breadth-first view of one process: overview, per-section element counts (with confirmed counts) and section status — without dumping every element.",
    parameters: {
      type: "OBJECT",
      properties: {
        slug: { type: "STRING", description: "The process slug." }
      },
      required: ["slug"]
    }
  },
  {
    name: "getProcessElements",
    description: "ADVISORY BOARD (read-only). Return the elements of one section/collection of a process (id + title + content).",
    parameters: {
      type: "OBJECT",
      properties: {
        slug: { type: "STRING", description: "The process slug." },
        collection: { type: "STRING", description: "The collection name, e.g. 'controls', 'process-steps'." }
      },
      required: ["slug", "collection"]
    }
  },
  {
    name: "searchProcesses",
    description: "ADVISORY BOARD (read-only). Keyword search across all accessible processes — matches element title, body and metadata. Returns capped hits with a snippet and the source {slug, id, section}.",
    parameters: {
      type: "OBJECT",
      properties: {
        query: { type: "STRING", description: "The keyword or phrase to search for." }
      },
      required: ["query"]
    }
  },
  {
    name: "createElement",
    description: "Create a new process element conforming to the JSON schema. The ID is automatically generated by the backend.",
    parameters: {
      type: "OBJECT",
      properties: {
        type: { type: "STRING", description: "The collection name, e.g. 'process-steps', 'exceptions', 'pain-points', 'roles', 'metrics'." },
        tempKey: { type: "STRING", description: "Optional. An ephemeral temporary key used to reference this element in other parallel tool calls during the same turn." },
        element: {
          type: "OBJECT",
          description: "The element payload containing metadata (meta) and content fields, conforming to the JSON schema. Do not include 'id' inside meta; it is auto-assigned.",
          properties: {
            meta: {
              type: "OBJECT",
              description: "Metadata fields (status, confidence, source, provenance, owner, etc.)",
              properties: {
                status: { type: "STRING", description: "Defaults to 'draft'." },
                confidence: { type: "STRING", description: "high, medium, or low" },
                source: { type: "STRING", description: "Verification source" },
                provenance: {
                  type: "OBJECT",
                  description: "Provenance mapping for each template heading block, e.g. { 'What happens': { source: 'elicited', evidence: 'quote' } }"
                }
              },
              required: ["source"]
            },
            content: {
              type: "OBJECT",
              description: "The domain-specific fields and blocks (title, description, inputs, outputs, etc.)"
            }
          },
          required: ["meta", "content"]
        }
      },
      required: ["type", "element"]
    }
  },
  {
    name: "createElements",
    description: "Author a whole run of elements in one call. Each spec carries a 'type' (collection name), an 'element' payload (same shape as createElement, no id), and an optional 'tempKey'. Elements may cross-reference each other within the batch via '@tempKey'. The backend assigns every id, resolves every '@tempKey', and returns per-type 'counts' (use these for your report — there is no separate manifest). A failing element is reported in 'errors' and skipped; the rest still write.",
    parameters: {
      type: "OBJECT",
      properties: {
        elements: {
          type: "ARRAY",
          description: "The element specs to create, in order.",
          items: {
            type: "OBJECT",
            properties: {
              type: { type: "STRING", description: "The collection name, e.g. 'market-trends', 'regulation', 'innovation-ideas'." },
              tempKey: { type: "STRING", description: "Optional ephemeral key so a later element in this batch can reference this one via '@tempKey'." },
              element: {
                type: "OBJECT",
                description: "The element payload (meta + content), conforming to the JSON schema. Do not include 'id'; it is auto-assigned.",
                properties: {
                  meta: { type: "OBJECT", description: "Metadata fields (status, confidence, source, provenance, etc.)" },
                  content: { type: "OBJECT", description: "The domain-specific fields and blocks." }
                },
                required: ["meta", "content"]
              }
            },
            required: ["type", "element"]
          }
        }
      },
      required: ["elements"]
    }
  },
  {
    name: "updateElement",
    description: "Update an existing process element by applying a deep merge patch.",
    parameters: {
      type: "OBJECT",
      properties: {
        id: { type: "STRING", description: "The unique ID of the element to update (e.g. 'PS-COB-001')." },
        patch: {
          type: "OBJECT",
          description: "JSON object containing updated fields in meta and/or content to merge into the element.",
          properties: {
            meta: { type: "OBJECT", description: "Metadata fields to update" },
            content: { type: "OBJECT", description: "Content fields to update" }
          }
        }
      },
      required: ["id", "patch"]
    }
  },
  {
    name: "checkConformance",
    description: "Run deterministic template-conformance checks on all elements in the process.",
    parameters: {
      type: "OBJECT",
      properties: {
        slug: { type: "STRING", description: "The process slug." }
      },
      required: ["slug"]
    }
  },
  {
    name: "checkTransitions",
    description: "Reconcile process-step transitions against exceptions to find orphans or broken links.",
    parameters: {
      type: "OBJECT",
      properties: {
        slug: { type: "STRING", description: "The process slug." }
      },
      required: ["slug"]
    }
  },
  {
    name: "applyLint",
    description: "Apply a set of lint findings: writes findings to the process JSON and reopens any implicated approved elements.",
    parameters: {
      type: "OBJECT",
      properties: {
        slug: { type: "STRING", description: "The process slug." },
        findings: {
          type: "ARRAY",
          description: "List of findings to write.",
          items: {
            type: "OBJECT",
            properties: {
              kind: { type: "STRING", description: "conformance, discrepancy, or question" },
              title: { type: "STRING", description: "Finding headline" },
              detail: { type: "STRING", description: "Detailed description or question" },
              elements: {
                type: "ARRAY",
                items: { type: "STRING" },
                description: "List of implicated element IDs"
              }
            },
            required: ["kind", "title", "detail", "elements"]
          }
        }
      },
      required: ["slug", "findings"]
    }
  },
  {
    name: "writeTargetReview",
    description: "Write the council-review result (the target-state review feedback) to the process. Id-stamps the items (R-001…) and marks each triage: pending. Used by the council-review skill.",
    parameters: {
      type: "OBJECT",
      properties: {
        reviewData: {
          type: "OBJECT",
          description: "{ ran: string[], items: [{ specialist, title, detail, targets: string[] }] }",
          properties: {
            ran: { type: "ARRAY", items: { type: "STRING" } },
            items: {
              type: "ARRAY",
              items: {
                type: "OBJECT",
                properties: {
                  specialist: { type: "STRING" },
                  title: { type: "STRING" },
                  detail: { type: "STRING" },
                  targets: { type: "ARRAY", items: { type: "STRING" } }
                },
                required: ["specialist", "title", "detail", "targets"]
              }
            }
          },
          required: ["ran", "items"]
        }
      },
      required: ["reviewData"]
    }
  },
  {
    name: "writeSummary",
    description: "Write one area's executive summary (an Amazon-style memo with exactly four ## headings: Introduction, Current state, What stands out, Recommendation) into the process's `summaries`, keyed by area. Used by the area-summary skill.",
    parameters: {
      type: "OBJECT",
      properties: {
        area: { type: "STRING", description: "The area id, e.g. 'as-is-process'." },
        summary: { type: "STRING", description: "The memo markdown with exactly the four headings in order." }
      },
      required: ["area", "summary"]
    }
  },
  {
    name: "scaffoldProcess",
    description: "Create a brand-new, empty process document (root meta + an empty overview). Used only by the new-process skill, in an unscoped session, before any content exists. Refuses to overwrite an existing process.",
    parameters: {
      type: "OBJECT",
      properties: {
        slug: { type: "STRING", description: "Deterministic kebab-case slug — the file name." },
        PROC: { type: "STRING", description: "Uppercase process abbreviation for element IDs, e.g. 'FRL'." },
        title: { type: "STRING", description: "The process title." },
        description: { type: "STRING", description: "One-line process description." }
      },
      required: ["slug", "PROC", "title"]
    }
  },
  {
    name: "writeIngestReport",
    description: "Write the document-ingest result into the process JSON's `ingest` field (the file ingested, created/updated element ids, and the conflicts/corrections the SME triages in the app). Stamps slug + generatedAt. The app's triage screen reads this. Used by the document-ingest skill.",
    parameters: {
      type: "OBJECT",
      properties: {
        report: {
          type: "OBJECT",
          description: "The ingest result.",
          properties: {
            file: { type: "STRING", description: "The source filename ingested." },
            created: { type: "ARRAY", items: { type: "STRING" }, description: "Ids of newly created elements." },
            updated: { type: "ARRAY", items: { type: "STRING" }, description: "Ids of updated elements." },
            conflicts: { type: "ARRAY", items: { type: "OBJECT" }, description: "{ element, field, documentSays, wikiSays } entries." },
            corrections: { type: "ARRAY", items: { type: "OBJECT" }, description: "{ element, field, removed } entries." }
          }
        }
      },
      required: ["report"]
    }
  },
  {
    name: "writeDtpReport",
    description: "Write a regenerated DTP and its critical-review report. Saves the Markdown as a new versioned file under raw-sources/<slug>/ (flagged generated), stamps finding ids (DTPF-…), and stores the report (generatedFile + findings) in the runtime store — never the wiki JSON. Returns the generated filename and finding count. Used by the dtp-regenerate skill.",
    parameters: {
      type: "OBJECT",
      properties: {
        report: {
          type: "OBJECT",
          description: "The regeneration result.",
          properties: {
            basis: { type: "STRING", description: "Always 'as-is' today." },
            sourceFile: { type: "STRING", description: "Original DTP filename the regeneration is based on (doc.ingest.file)." },
            markdown: { type: "STRING", description: "The full regenerated DTP, as Markdown." },
            findings: {
              type: "ARRAY",
              description: "Critical-review findings — the original DTP measured against the corrected As-Is wiki.",
              items: {
                type: "OBJECT",
                properties: {
                  kind: { type: "STRING", description: "One of: outdated | missing | contradiction | added." },
                  headline: { type: "STRING", description: "One-line plain-English summary of the discrepancy, for scanning a list." },
                  dtpSays: { type: "STRING", description: "What the original DTP states (or '—')." },
                  wikiSays: { type: "STRING", description: "What the corrected As-Is wiki holds." },
                  elements: { type: "ARRAY", items: { type: "STRING" }, description: "Implicated wiki element ids." },
                  severity: { type: "STRING", description: "One of: high | medium | low." },
                  rationale: { type: "STRING", description: "One line on why this severity / why it matters (e.g. 'control gap', 'wrong owner on a key step')." },
                  suggestedDisposition: { type: "STRING", description: "Suggested call: 'accepted' = a DTP correction; 'dismissed' = more likely a wiki issue to reconcile." }
                },
                required: ["kind", "headline", "wikiSays"]
              }
            },
            coverage: {
              type: "OBJECT",
              description: "What the run reviewed, for the coverage map.",
              properties: {
                dtpSections: { type: "ARRAY", items: { type: "STRING" }, description: "The DTP sections/headings the run walked." }
              }
            }
          },
          required: ["sourceFile", "markdown"]
        }
      },
      required: ["report"]
    }
  },
  {
    name: "writeDtpComparison",
    description: "Record a comparison-only DTP run: the chosen original DTP critically reviewed against the corrected As-Is wiki. Stamps finding ids (DTPF-…) and stores the findings + pointer in the runtime store as a new past-comparison entry — no Markdown is generated and no artifact is written. Returns the run id and finding count. Used by the dtp-compare skill.",
    parameters: {
      type: "OBJECT",
      properties: {
        report: {
          type: "OBJECT",
          description: "The comparison result.",
          properties: {
            sourceFile: { type: "STRING", description: "The DTP filename reviewed (under raw-sources/<slug>/)." },
            findings: {
              type: "ARRAY",
              description: "Critical-review findings — the chosen DTP measured against the corrected As-Is wiki.",
              items: {
                type: "OBJECT",
                properties: {
                  kind: { type: "STRING", description: "One of: outdated | missing | contradiction | added." },
                  headline: { type: "STRING", description: "One-line plain-English summary of the discrepancy, for scanning a list." },
                  dtpSays: { type: "STRING", description: "What the original DTP states (or '—')." },
                  wikiSays: { type: "STRING", description: "What the corrected As-Is wiki holds." },
                  elements: { type: "ARRAY", items: { type: "STRING" }, description: "Implicated wiki element ids." },
                  severity: { type: "STRING", description: "One of: high | medium | low." },
                  rationale: { type: "STRING", description: "One line on why this severity / why it matters (e.g. 'control gap', 'wrong owner on a key step')." },
                  suggestedDisposition: { type: "STRING", description: "Suggested call: 'accepted' = a DTP correction; 'dismissed' = more likely a wiki issue to reconcile." }
                },
                required: ["kind", "headline", "wikiSays"]
              }
            },
            coverage: {
              type: "OBJECT",
              description: "What the run reviewed, for the coverage map.",
              properties: {
                dtpSections: { type: "ARRAY", items: { type: "STRING" }, description: "The DTP sections/headings the run walked." }
              }
            }
          },
          required: ["sourceFile", "findings"]
        }
      },
      required: ["report"]
    }
  },
  {
    name: "writeDtpSummary",
    description: "Store the executive-summary memo for one past DTP comparison run, keyed by its run id. Markdown. Stored in the runtime store — never the wiki JSON. Used by the dtp-summary skill.",
    parameters: {
      type: "OBJECT",
      properties: {
        runId: { type: "STRING", description: "The DTP run id the memo summarises (e.g. DTP-REGEN-003)." },
        summary: { type: "STRING", description: "The executive-summary memo, as Markdown." }
      },
      required: ["runId", "summary"]
    }
  },
  {
    name: "clearConflicts",
    description: "Empty the `conflicts` array on the process JSON's `ingest` report once every conflict has been resolved, so the triage screen stops flagging them. No-op if there is no ingest report. Used by the conflict-resolution skill's close-out.",
    parameters: {
      type: "OBJECT",
      properties: {
        slug: { type: "STRING", description: "The process slug." }
      },
      required: ["slug"]
    }
  },
  {
    name: "createNote",
    description: "Post a note onto an element's discussion thread (the process JSON's `notes`, keyed by element id). Used by the comment-review skill to post its closing analyst summary. The id and timestamp are assigned by the backend.",
    parameters: {
      type: "OBJECT",
      properties: {
        elementId: { type: "STRING", description: "The element the note is attached to, e.g. 'PS-COB-001'." },
        author: { type: "STRING", description: "Who is posting — the analyst / SME name from the session context." },
        content: { type: "STRING", description: "The note text." },
        type: { type: "STRING", description: "Optional note kind, e.g. 'summary' for the analyst close-out." },
        replyTo: { type: "STRING", description: "Optional id of the note this replies to." }
      },
      required: ["elementId", "content"]
    }
  },
  {
    name: "resolveNotes",
    description: "Mark the given note ids resolved across the process's discussion threads (sets resolved/resolvedBy/resolvedAt), so they no longer show as open comments. Used by the comment-review skill once each comment has a decision.",
    parameters: {
      type: "OBJECT",
      properties: {
        noteIds: { type: "ARRAY", items: { type: "STRING" }, description: "The note ids to mark resolved." },
        resolvedBy: { type: "STRING", description: "Optional — who resolved them (the analyst / SME name); defaults to 'SME'." }
      },
      required: ["noteIds"]
    }
  },
  {
    name: "setApproval",
    description: "Set an element's approval state (in-progress | approved | rejected). The approval gate is enforced: 'approved' is refused while any heading's provenance is still 'proposed'/'web'. Used by foundational-run and the specialists when the SME signs an element off.",
    parameters: {
      type: "OBJECT",
      properties: {
        id: { type: "STRING", description: "The element id to set approval on, e.g. 'PS-COB-001'." },
        status: { type: "STRING", description: "in-progress | approved | rejected." },
        approver: { type: "STRING", description: "The SME name signing it off (the session context)." }
      },
      required: ["id", "status"]
    }
  },
  {
    name: "buildQueue",
    description: "Start a fresh foundational-run: build the ordered walk queue (the overview first, then current-state elements, process-gaps last) and persist the cursor. Returns position/total/done/current and the canonical outcomes_line. Used by foundational-run when no run state exists.",
    parameters: {
      type: "OBJECT",
      properties: { slug: { type: "STRING", description: "The process slug." } },
      required: ["slug"]
    }
  },
  {
    name: "startSession",
    description: "Start a fresh qer-session: build the cursor over the fixed QER step sequence and persist it. Returns position/total/done/current (the step name). Used by qer-session when no session state exists.",
    parameters: {
      type: "OBJECT",
      properties: { slug: { type: "STRING", description: "The process slug." } },
      required: ["slug"]
    }
  },
  {
    name: "getSessionStatus",
    description: "Read the resumable cursor for the process — returns exists/position/total/done/current, plus (foundational only) the canonical outcomes_line while running and closeout_template once done. `kind` selects which cursor: 'foundational' (default, the element walk) or 'qer' (the step sequence).",
    parameters: {
      type: "OBJECT",
      properties: {
        slug: { type: "STRING", description: "The process slug." },
        kind: { type: "STRING", description: "'foundational' (default) or 'qer'." }
      },
      required: ["slug"]
    }
  },
  {
    name: "advanceSession",
    description: "Advance the resumable cursor by one item and persist it; returns the next position/total/done/current. `kind` selects which cursor: 'foundational' (default) or 'qer'.",
    parameters: {
      type: "OBJECT",
      properties: {
        slug: { type: "STRING", description: "The process slug." },
        kind: { type: "STRING", description: "'foundational' (default) or 'qer'." }
      },
      required: ["slug"]
    }
  },
];

// SESSIONS_MAP_PATH tracks process slugs across session IDs
const SESSIONS_MAP_PATH = path.join(process.cwd(), "wiki", "processes", ".sessions.json");

function saveSessionSlug(sessionId: string, slug: string, activeSkill: string | null = null) {
  try {
    const dir = path.dirname(SESSIONS_MAP_PATH);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    const data = fs.existsSync(SESSIONS_MAP_PATH) ? JSON.parse(fs.readFileSync(SESSIONS_MAP_PATH, "utf8")) : {};
    data[sessionId] = { slug, activeSkill };
    fs.writeFileSync(SESSIONS_MAP_PATH, JSON.stringify(data, null, 2), "utf8");
  } catch (e) {
    console.error("Failed to save session slug map:", e);
  }
}

function appendToCentralLog(sessionId: string, slug: string | undefined, role: "User" | "Model" | "System" | "Error", text: string) {
  try {
    const logDir = path.join(process.cwd(), "logs");
    if (!fs.existsSync(logDir)) {
      fs.mkdirSync(logDir, { recursive: true });
    }
    const logPath = path.join(logDir, "assistant.log");
    const ts = new Date().toISOString();
    const sessionPart = sessionId.slice(0, 8);
    const slugPart = slug ? ` [${slug}]` : "";
    const logLine = `[${ts}] [${sessionPart}]${slugPart} [${role}] ${text}\n`;
    fs.appendFileSync(logPath, logLine, "utf8");
  } catch (err) {
    console.error("Failed to append to central log:", err);
  }
}

function getSessionInfo(sessionId: string): { slug: string | null; activeSkill: string | null } {
  try {
    if (!fs.existsSync(SESSIONS_MAP_PATH)) return { slug: null, activeSkill: null };
    const data = JSON.parse(fs.readFileSync(SESSIONS_MAP_PATH, "utf8"));
    const entry = data[sessionId];
    if (typeof entry === "string") {
      return { slug: entry, activeSkill: null };
    } else if (entry && typeof entry === "object") {
      return { slug: entry.slug || null, activeSkill: entry.activeSkill || null };
    }
    return { slug: null, activeSkill: null };
  } catch (e) {
    console.error("Failed to read session slug map:", e);
    return { slug: null, activeSkill: null };
  }
}

function generateDocumentMap(doc: any, activeCollection: string | null = null, activeElementId: string | null = null): any {
  const result: any = { meta: doc.meta, content: doc.content }; 
  const schemaReferences: Record<string, string[]> = {
    "process-step": ["roles", "systems"], 
    "system": ["integrations", "roles"],
    "role": ["systems", "controls"]
  };
  
  const activeElement = activeCollection && activeElementId 
    ? doc[activeCollection]?.find((el: any) => el.meta?.id === activeElementId)
    : null;
  const referencedCollections = activeElement ? (schemaReferences[activeElement.meta?.type] || []) : [];
  
  Object.keys(doc).forEach(key => {
    if (!Array.isArray(doc[key])) return;
    
    if (activeCollection && key === activeCollection) {
      result[key] = doc[key].map((el: any) => {
        if (el.meta?.id === activeElementId) {
          return el; // full-expand
        } else {
          return { meta: { id: el.meta?.id }, content: { title: el.content?.title } }; // list peers
        }
      });
    } 
    else if (referencedCollections.includes(key)) {
      result[key] = doc[key].map((el: any) => {
        return { meta: { id: el.meta?.id }, content: { title: el.content?.title } };
      });
    } 
    else {
      // Default: list process steps at a high level if no element is active
      if (!activeElementId && key === "process-steps") {
        result[key] = doc[key].map((el: any) => {
          return { meta: { id: el.meta?.id }, content: { title: el.content?.title } };
        });
      } else {
        result[key] = doc[key].length;
      }
    }
  });
  
  return result;
}

function customStringify(obj: any, indent = ""): string {
  if (Array.isArray(obj)) {
    if (obj.length === 0) return "[]";
    let out = "[\n";
    for (let i = 0; i < obj.length; i++) {
      let isLast = i === obj.length - 1;
      const isListItem = obj[i] && obj[i].meta && obj[i].meta.id && Object.keys(obj[i]).length === 2 && obj[i].content && obj[i].content.title;
      
      if (isListItem) {
        out += `${indent}  { "meta": { "id": "${obj[i].meta.id}" /*...*/ }, "content": { "title": "${obj[i].content.title}" /*...*/ } }${isLast ? "" : ","}\n`;
      } else {
        const lines = JSON.stringify(obj[i], null, 2).split('\n');
        out += lines.map((l, idx) => (idx === 0 ? indent + "  " + l : indent + "  " + l)).join('\n') + (isLast ? "" : ",") + "\n";
      }
    }
    out += indent + "]";
    return out;
  }
  
  if (typeof obj === "object" && obj !== null) {
    let out = "{\n";
    const keys = Object.keys(obj);
    for (let i = 0; i < keys.length; i++) {
      const k = keys[i];
      let isLast = i === keys.length - 1;
      if (typeof obj[k] === "number") {
         out += `${indent}  "${k}": ${obj[k]} /*...*/${isLast ? "" : ","}\n`;
      } else if (Array.isArray(obj[k])) {
         out += `${indent}  "${k}": ${customStringify(obj[k], indent + "  ")}${isLast ? "" : ","}\n`;
      } else {
         out += `${indent}  "${k}": ${JSON.stringify(obj[k], null, 2).replace(/\n/g, '\n' + indent + '  ')}${isLast ? "" : ","}\n`;
      }
    }
    out += indent + "}";
    return out;
  }
  return JSON.stringify(obj);
}

/**
 * Build a fresh process JSON document — root `meta` plus an empty `overview`
 * `content` — for the new-process scaffolding step. The overview id is
 * `${PROC}-001`; `generateNextId` derives the PROC abbreviation from it, so
 * every later element gets `<prefix>-${PROC}-<seq>` ids without storing PROC
 * separately. Shared by both providers (gemini-worker + claude-mcp-server).
 */
export function buildProcessDoc(PROC: string, title: string, description: string): any {
  return {
    meta: {
      id: `${PROC}-001`,
      type: "process",
      section: "overview",
      status: "draft",
      confidence: "low",
      source: null,
      docStatus: "empty",
    },
    content: {
      title,
      description: description || null,
      processOwner: null,
      trigger: null,
      frequency: null,
      scopeIn: null,
      scopeOut: null,
      processInput: null,
      processOutput: null,
    },
  };
}

export class GeminiWorker implements IProcessWorker {
  readonly id = crypto.randomUUID();
  sessionId: string | null = null;
  busy = false;
  lastUsed = Date.now();
  alive = true;
  private slug: string | undefined;
  private activeSkill: string | null = null;
  // The session's signed-in identity — gates every slug-bearing tool by
  // canAccess (R16) so a session only reaches processes its user can see.
  // Null when no identity was provided (legacy callers); access stays open
  // then, exactly like the out-of-process MCP server.
  private user: { username: string; isAdmin: boolean } | null;

  private ai: GoogleGenAI;
  private history: Array<any> = [];

  constructor(resumeId?: string | null, user?: { username: string; isAdmin: boolean } | null) {
    this.user = user ?? null;
    this.sessionId = resumeId || crypto.randomUUID();
    this.ai = new GoogleGenAI({
      apiKey: process.env.GEMINI_API_KEY || undefined,
    });
    if (this.sessionId) {
      const info = getSessionInfo(this.sessionId);
      this.slug = info.slug || undefined;
      this.activeSkill = info.activeSkill || null;
    }
  }

  /** R16 — whether this session's user may reach `slug`. Open when no identity
   *  is present (legacy), since the HTTP route is the trust boundary. */
  private hasAccess(slug: string): boolean {
    if (!this.user) return true;
    return canAccess(this.user, slug);
  }
  private assertAccess(slug: string): void {
    if (!this.hasAccess(slug)) {
      throw new Error(`Access denied: you do not have access to process "${slug}".`);
    }
  }

  private buildSystemInstruction(message: string): string {
    let instruction = "";

    // 1. Prepend CORE_SYSTEM_PROMPT.md if available
    const corePromptPath = path.join(process.cwd(), ".claude", "skills", "CORE_SYSTEM_PROMPT.md");
    if (fs.existsSync(corePromptPath)) {
      try {
        instruction += fs.readFileSync(corePromptPath, "utf8") + "\n\n";
      } catch (e) {
        console.error("Failed to read CORE_SYSTEM_PROMPT.md:", e);
      }
    } else {
      instruction += "You are Processminer, an AI-native process documentation assistant.\n\n";
    }

    // 2. Append Core Process Schema
    const schemaPath = path.join(process.cwd(), "schema", "process-schema.json");
    if (fs.existsSync(schemaPath)) {
      try {
        const schema = fs.readFileSync(schemaPath, "utf8");
        instruction += `### Core Process Schema:\nUse this schema as your single source of truth for element types, sections, frontmatter fields, and relations:\n${schema}\n\n`;
      } catch {
        /* fallback */
      }
    }

    // 3. Dynamic Skill Elicitation: Scan for any of the 21 skill names
    let activeSkill: string | null = this.activeSkill;
    const msgLower = message.toLowerCase();

    let foundSkill: string | null = null;
    for (const skill of SKILL_NAMES) {
      // If we are in a scoped session (this.slug is set), ignore "new-process" since it's only for unscoped creation.
      if (this.slug && skill === "new-process") {
        continue;
      }
      if (msgLower.includes(skill) || msgLower.includes(skill.replace("-", " "))) {
        foundSkill = skill;
        break;
      }
    }

    if (foundSkill) {
      activeSkill = foundSkill;
    } else if (!activeSkill) {
      if (msgLower.includes("lint")) activeSkill = "run-lint";
      else if (msgLower.includes("ingest")) activeSkill = "document-ingest";
      else if (!this.slug && msgLower.includes("new-process")) activeSkill = "new-process";
      else if (msgLower.includes("foundational")) activeSkill = "foundational-run";
      else if (msgLower.includes("conflict")) activeSkill = "conflict-resolution";
      
      // Default to process-specialist if it mentions steps/process or is a general documentation request,
      // or if we are in a scoped session.
      if (!activeSkill && (this.slug || msgLower.includes("step") || msgLower.includes("process") || msgLower.includes("document"))) {
        activeSkill = "process-specialist";
      }
    }

    // Force process-specialist if we are in a scoped session and activeSkill is new-process or not set
    if (this.slug && (activeSkill === "new-process" || !activeSkill)) {
      activeSkill = "process-specialist";
    }

    this.activeSkill = activeSkill;
    if (this.sessionId && this.slug && this.activeSkill) {
      saveSessionSlug(this.sessionId, this.slug, this.activeSkill);
    }

    if (activeSkill) {
      const skillPath = path.join(process.cwd(), ".claude", "skills", activeSkill, "SKILL.md");
      if (fs.existsSync(skillPath)) {
        try {
          const skillInstruction = fs.readFileSync(skillPath, "utf8");
          instruction += `### Active Specialist Guidelines (${activeSkill}):\nFollow these procedures strictly:\n${skillInstruction}\n\n`;
        } catch {
          /* fallback */
        }
      }
    }

    // 4. Dynamically append the abridged JSON Document Map context
    if (this.slug) {
      const processFilePath = path.join(process.cwd(), "wiki", "processes", `${this.slug}.json`);
      if (fs.existsSync(processFilePath)) {
        try {
          const doc = JSON.parse(fs.readFileSync(processFilePath, "utf8"));
          let activeCollection = null;
          let activeId = null;
          // Attempt to read from qer-state.json
          const qerStatePath = path.join(process.cwd(), "wiki", "processes", this.slug, "qer-state.json");
          if (fs.existsSync(qerStatePath)) {
            const qerState = JSON.parse(fs.readFileSync(qerStatePath, "utf8"));
            activeCollection = qerState.section;
            activeId = qerState.id;
          }
          const docMap = generateDocumentMap(doc, activeCollection, activeId);
          instruction += `### Current Document Map:\nThis is the current state of the document you are authoring:\n${customStringify(docMap)}\n\n`;
        } catch (e) {
          console.error("Failed to build Document Map in system instructions:", e);
        }
      }
    }

    return instruction;
  }

  async *runTurn(message: string, skill?: string | null): AsyncGenerator<WorkerEvent> {
    if (!this.alive) {
      throw new Error("This assistant session is no longer running.");
    }
    if (this.busy) {
      throw new Error("This assistant session is already handling a turn.");
    }
    this.busy = true;
    this.lastUsed = Date.now();

    if (skill) {
      this.activeSkill = skill;
    }

    // Extract process slug from scope preamble if present, or rehydrate from sessions map
    if (this.sessionId) {
      const match = message.match(/wiki\/processes\/([^/]+)\//);
      if (match) {
        this.slug = match[1];
        saveSessionSlug(this.sessionId, this.slug, this.activeSkill);
      } else if (!this.slug) {
        const info = getSessionInfo(this.sessionId);
        this.slug = info.slug || undefined;
        if (!this.activeSkill) {
          this.activeSkill = info.activeSkill || null;
        }
      }
    }

    try {
      // R16 — the session's scoped process must be one the user can access.
      // Blocks a forged scope preamble pointing this session at a governed
      // process the user can't open. (Cross-process read tools are gated
      // separately in the dispatch below.)
      if (this.slug) this.assertAccess(this.slug);

      const systemInstruction = this.buildSystemInstruction(message);

      this.history.push({
        role: "user",
        parts: [{ text: message }],
      });

      let loopActive = true;
      let turns = 0;
      const MAX_TURNS = 35; // Loop cap to prevent infinity recursion

      const activeTools = toolDeclarations;

      appendToCentralLog(this.sessionId || "unknown", this.slug, "User", `Message:\n${message}`);
      appendToCentralLog(this.sessionId || "unknown", this.slug, "System", `Skill: ${this.activeSkill} | Active Tools: ${activeTools.map(t => t.name).join(", ")}`);

      while (loopActive && turns < MAX_TURNS) {
        if (!this.alive) {
          break;
        }
        turns++;

        // Request content generation (with native tool definitions)
        const response = await this.ai.models.generateContent({
          model: SESSION_MODEL,
          contents: this.history,
          config: {
            systemInstruction,
            tools: [{ functionDeclarations: activeTools }]
          }
        });

        const calls = response.functionCalls;

        if (calls && calls.length > 0) {
          console.log("[gemini-worker] Raw parts from API:", JSON.stringify(response.candidates?.[0]?.content?.parts, null, 2));
          calls.forEach((c) => {
            appendToCentralLog(this.sessionId || "unknown", this.slug, "Model", `Tool Call: ${c.name}(\n${JSON.stringify(c.args, null, 2)}\n)`);
          });
          // 1. Yield tool use events to update the client's progress UI
          yield {
            type: "assistant",
            message: {
              content: calls.map((c, idx) => ({
                type: "tool_use",
                name: c.name,
                input: c.args as Record<string, unknown>,
                id: `call_${turns}_${idx}`
              }))
            }
          };

          const candidateParts = response.candidates?.[0]?.content?.parts || [];
          const functionCallParts = candidateParts.filter((p: any) => p.functionCall);

          // 2. Iterate and execute requested tools locally in sequence (sequential singleton pattern)
          const tempKeyMap = new Map<string, string>();
          const schema = getSchema();
          
          let doc: any = null;
          let processFilePath = "";
          if (this.slug) {
            processFilePath = path.join(process.cwd(), "wiki", "processes", `${this.slug}.json`);
            if (fs.existsSync(processFilePath)) {
              try {
                doc = JSON.parse(fs.readFileSync(processFilePath, "utf8"));
              } catch (e: any) {
                console.error("Failed to parse process json:", e);
              }
            }
          }

          const userParts: any[] = [];

          for (let idx = 0; idx < calls.length; idx++) {
            // Reload doc from disk to get the latest state after any writes
            if (this.slug && fs.existsSync(processFilePath)) {
              try {
                doc = JSON.parse(fs.readFileSync(processFilePath, "utf8"));
              } catch (e: any) {
                console.error("Failed to parse process json inside loop:", e);
              }
            }

            const call = calls[idx];
            const originalName = functionCallParts[idx]?.functionCall?.name || call.name || "";
            const isExpandElement = originalName === "expandElement";
            const isCreateElement = originalName === "createElement";
            const isUpdateElement = originalName === "updateElement";

            let resultText = "";
            try {
              console.log(`[gemini-worker] Executing tool sequentially: ${originalName}`, call.args);
              const args = (call.args || {}) as any;

              if (originalName === "listAccessibleProcesses") {
                // Advisory Board (read-only) — cross-process, but only the
                // processes this session's user may see (R16).
                resultText = JSON.stringify(listProcesses().filter((p) => this.hasAccess(p.slug)), null, 2);
              } else if (originalName === "searchProcesses") {
                // Scope the search to accessible slugs so hits never leak from
                // governed processes the user can't open.
                const allowed = listProcesses().map((p) => p.slug).filter((s) => this.hasAccess(s));
                resultText = JSON.stringify(searchProcesses(String(args.query || ""), allowed), null, 2);
              } else if (originalName === "getProcessSummary") {
                this.assertAccess(String(args.slug || ""));
                const s = getProcessSummary(String(args.slug || ""));
                if (!s) throw new Error(`Process not found: ${args.slug}`);
                resultText = JSON.stringify(s, null, 2);
              } else if (originalName === "getProcessElements") {
                this.assertAccess(String(args.slug || ""));
                const els = getProcessElements(String(args.slug || ""), String(args.collection || ""));
                if (els === null) throw new Error(`Process not found: ${args.slug}`);
                resultText = JSON.stringify({ slug: args.slug, collection: args.collection, elements: els }, null, 2);
              } else if (originalName === "scaffoldProcess") {
                const newSlug = String(args.slug || "").trim();
                const PROC = String(args.PROC || "").toUpperCase().trim();
                const title = String(args.title || "").trim();
                const description = String(args.description || "");
                if (!/^[a-z0-9]+(-[a-z0-9]+)*$/.test(newSlug)) throw new Error("slug must be kebab-case.");
                if (!/^[A-Z]{2,6}$/.test(PROC)) throw new Error("PROC must be 2–6 uppercase letters.");
                if (!title) throw new Error("title is required.");
                const newPath = path.join(process.cwd(), "wiki", "processes", `${newSlug}.json`);
                if (fs.existsSync(newPath)) throw new Error(`A process already exists for slug: ${newSlug}`);
                const newDoc = buildProcessDoc(PROC, title, description);
                atomicWriteFileSync(newPath, JSON.stringify(newDoc, null, 2) + "\n");
                // Scope this session to the freshly created process for subsequent turns.
                this.slug = newSlug;
                if (this.sessionId) saveSessionSlug(this.sessionId, this.slug, this.activeSkill);
                resultText = JSON.stringify({ ok: true, slug: newSlug, id: newDoc.meta.id, created: true }, null, 2);
              } else if (isExpandElement) {
                const type = args.type;
                const id = args.id;
                if (!doc) {
                  throw new Error("Process document context not loaded or slug is missing.");
                }
                if (!id) {
                  const list = doc[type] || [];
                  const elements = list.map((el: any) => ({
                    id: el.meta?.id,
                    title: el.content?.title
                  }));
                  resultText = JSON.stringify({ type, elements }, null, 2);
                } else {
                  const list = doc[type] || [];
                  const element = list.find((el: any) => el.meta?.id === id);
                  if (!element) {
                    throw new Error(`Element ${id} not found in collection ${type}.`);
                  }
                  resultText = JSON.stringify(element, null, 2);
                }
              } else if (isCreateElement) {
                const type = args.type;
                const tempKey = args.tempKey;

                if (!doc) {
                  throw new Error("Process document context not loaded or slug is missing.");
                }

                const built = buildElement(doc, schema, type, args.element, tempKeyMap);
                if (!built.ok || !built.fullElement) {
                  resultText = `Error: Element validation failed:\n- ${(built.issues || []).join("\n- ")}`;
                } else {
                  applyElement(doc, type, built.fullElement, built.singularType!);
                  // Write directly to disk immediately
                  atomicWriteFileSync(processFilePath, JSON.stringify(doc, null, 2) + "\n");

                  if (tempKey) {
                    const cleanKey = tempKey.startsWith("@") ? tempKey.slice(1) : tempKey;
                    tempKeyMap.set(cleanKey, built.id!);
                  }

                  resultText = JSON.stringify({ ok: true, id: built.id, element: built.fullElement }, null, 2);
                }
              } else if (originalName === "createElements") {
                if (!doc) {
                  throw new Error("Process document context not loaded or slug is missing.");
                }
                const elements = (args.elements || []) as BatchSpec[];
                if (!Array.isArray(elements) || elements.length === 0) {
                  throw new Error("createElements requires a non-empty `elements` array.");
                }
                const batch = createElementsBatch(doc, schema, elements);
                // Persist whatever wrote successfully (errors are isolated, the rest still land).
                atomicWriteFileSync(processFilePath, JSON.stringify(doc, null, 2) + "\n");
                // Carry resolved tempKeys into the turn-level map so later calls can reference them.
                for (const c of batch.created) {
                  if (c.tempKey) {
                    const cleanKey = c.tempKey.startsWith("@") ? c.tempKey.slice(1) : c.tempKey;
                    tempKeyMap.set(cleanKey, c.id);
                  }
                }
                resultText = JSON.stringify(
                  { ok: batch.ok, created: batch.created, counts: batch.counts, errors: batch.errors },
                  null,
                  2
                );
              } else if (isUpdateElement) {
                const id = args.id;
                let patch = args.patch || {};

                if (!doc) {
                  throw new Error("Process document context not loaded or slug is missing.");
                }

                // Resolve tempKey in patch payload
                patch = replaceTempKeys(patch, tempKeyMap);

                // Resolve target ID if it's a tempKey reference
                let targetId = id;
                if (targetId.startsWith("@")) {
                  const key = targetId.slice(1);
                  if (tempKeyMap.has(key)) {
                    targetId = tempKeyMap.get(key)!;
                  }
                }

                // Call the unified updateElement helper function which validates and writes directly to disk
                const res = await updateElement(this.slug!, targetId, patch);
                if (!res.ok) {
                  resultText = `Error: Element validation failed:\n- ${res.error}`;
                } else {
                  resultText = JSON.stringify({ ok: true, id: targetId, element: res.element }, null, 2);
                }
              } else if (originalName === "checkConformance") {
                if (!doc) {
                  throw new Error("Process document context not loaded or slug is missing.");
                }
                const elements: any[] = [];
                for (const [key, val] of Object.entries(doc)) {
                  if (!Array.isArray(val)) continue;
                  
                  let singularType = "";
                  for (const [t, def] of Object.entries(schema.elementTypes)) {
                    if ((def as any).section === key) {
                      singularType = t;
                      break;
                    }
                  }
                  if (!singularType) continue;
                  const info = schema.elementTypes[singularType];
                  
                  for (const el of val) {
                    const page = jsonElementToWikiPage(el, info);
                    elements.push(page);
                  }
                }
                const findings = checkConformance(elements, schema);
                resultText = JSON.stringify(findings, null, 2);
              } else if (originalName === "checkTransitions") {
                if (!doc) {
                  throw new Error("Process document context not loaded or slug is missing.");
                }
                const findings: any[] = [];
                const steps = doc["process-steps"] || [];
                const exceptions = doc["exceptions"] || [];
                
                const exceptionIds = new Set(exceptions.map((e: any) => e.meta?.id).filter(Boolean));
                const stepIds = new Set(steps.map((s: any) => s.meta?.id).filter(Boolean));
                const targetedExceptions = new Set<string>();
                
                let n = 0;
                for (const step of steps) {
                  const transitions = step.content?.transitions || [];
                  for (const t of transitions) {
                    const targetId = transitionTarget(t); // R7: accepts object or string form
                    if (targetId) {
                      if (targetId.startsWith("EX-")) {
                        targetedExceptions.add(targetId);
                        if (!exceptionIds.has(targetId)) {
                          n++;
                          findings.push({
                            id: `T-${n}`,
                            kind: "discrepancy",
                            title: `${step.content?.title || step.meta?.id} (${step.meta?.id})`,
                            detail: `Transitions to exception ${targetId} which does not exist in the document.`,
                            elements: [step.meta?.id]
                          });
                        }
                      }
                    }
                  }
                }
                
                for (const ex of exceptions) {
                  const exId = ex.meta?.id;
                  if (exId && !targetedExceptions.has(exId)) {
                    n++;
                    findings.push({
                      id: `T-${n}`,
                      kind: "discrepancy",
                      title: `${ex.content?.title || exId} (${exId})`,
                      detail: `Orphan exception — no process-step transition leads to this exception.`,
                      elements: [exId]
                    });
                  }
                }
                resultText = JSON.stringify(findings, null, 2);
              } else if (originalName === "applyLint") {
                const findings = args.findings || [];
                if (!doc) {
                  throw new Error("Process document context not loaded or slug is missing.");
                }
                
                const enrichedFindings = findings.map((f: any, i: number) => ({
                  ...f,
                  id: `F-${i + 1}`
                }));

                const lintReport = {
                  generatedAt: new Date().toISOString(),
                  slug: this.slug,
                  summary: {
                    conformance: enrichedFindings.filter((f: any) => f.kind === "conformance").length,
                    discrepancy: enrichedFindings.filter((f: any) => f.kind === "discrepancy").length,
                    question: enrichedFindings.filter((f: any) => f.kind === "question").length
                  },
                  findings: enrichedFindings,
                  reopens: [] as string[]
                };

                const reopens: string[] = [];
                for (const finding of enrichedFindings) {
                  if (Array.isArray(finding.elements)) {
                    for (const elId of finding.elements) {
                      for (const [key, val] of Object.entries(doc)) {
                        if (!Array.isArray(val)) continue;
                        const idx = val.findIndex((el: any) => el.meta?.id === elId);
                        if (idx !== -1) {
                          const el = val[idx];
                          if (el.meta?.approval === "approved") {
                            el.meta.approval = "in-progress";
                            el.meta.approvalBy = "run-lint";
                            el.meta.approvalDate = new Date().toISOString().slice(0, 10);
                            if (!reopens.includes(elId)) {
                              reopens.push(elId);
                            }
                          }
                        }
                      }
                    }
                  }
                }
                lintReport.reopens = reopens;
                // R9: the lint report is runtime state — store it above the wiki.
                writeRuntime(this.slug!, { lint: lintReport as any });
                delete doc.lint; // guardrail: lint never lives in the wiki JSON

                // Write directly to disk immediately (element re-opens only)
                atomicWriteFileSync(processFilePath, JSON.stringify(doc, null, 2) + "\n");

                resultText = JSON.stringify({
                  ok: true,
                  findingsCount: enrichedFindings.length,
                  reopenedCount: reopens.length,
                  summary: lintReport.summary
                }, null, 2);
              } else if (originalName === "writeTargetReview") {
                if (!doc) throw new Error("Process document context not loaded or slug is missing.");
                doc.targetReview = buildTargetReview(this.slug!, args.reviewData);
                atomicWriteFileSync(processFilePath, JSON.stringify(doc, null, 2) + "\n");
                resultText = JSON.stringify({ ok: true, items: doc.targetReview.items.length }, null, 2);
              } else if (originalName === "writeSummary") {
                if (!doc) throw new Error("Process document context not loaded or slug is missing.");
                const parts = parseSummaryParts(args.summary || "");
                if (!doc.summaries || typeof doc.summaries !== "object") doc.summaries = {};
                doc.summaries[args.area] = { parts, generatedAt: new Date().toISOString() };
                atomicWriteFileSync(processFilePath, JSON.stringify(doc, null, 2) + "\n");
                resultText = JSON.stringify({ ok: true, area: args.area, parts: parts.length }, null, 2);
              } else if (originalName === "writeIngestReport") {
                if (!doc) throw new Error("Process document context not loaded or slug is missing.");
                doc.ingest = buildIngestReport(this.slug!, args.report);
                atomicWriteFileSync(processFilePath, JSON.stringify(doc, null, 2) + "\n");
                resultText = JSON.stringify({ ok: true, created: doc.ingest.created.length, updated: doc.ingest.updated.length, conflicts: doc.ingest.conflicts.length, corrections: doc.ingest.corrections.length }, null, 2);
              } else if (originalName === "writeDtpReport") {
                if (!this.slug) throw new Error("Process document context not loaded or slug is missing.");
                // Writes the .md artifact + runtime report; never the process JSON.
                const res = writeDtpReport(this.slug, args.report ?? {});
                resultText = JSON.stringify({ ok: true, ...res }, null, 2);
              } else if (originalName === "writeDtpComparison") {
                if (!this.slug) throw new Error("Process document context not loaded or slug is missing.");
                // Review-only run: stores findings, writes no artifact, never the JSON.
                const res = writeDtpComparison(this.slug, args.report ?? {});
                resultText = JSON.stringify({ ok: true, ...res }, null, 2);
              } else if (originalName === "writeDtpSummary") {
                if (!this.slug) throw new Error("Process document context not loaded or slug is missing.");
                const ok = setDtpSummary(this.slug, String(args.runId ?? ""), String(args.summary ?? ""));
                resultText = JSON.stringify({ ok }, null, 2);
              } else if (originalName === "clearConflicts") {
                if (!doc) throw new Error("Process document context not loaded or slug is missing.");
                const { cleared } = clearIngestConflicts(doc);
                atomicWriteFileSync(processFilePath, JSON.stringify(doc, null, 2) + "\n");
                resultText = JSON.stringify({ ok: true, cleared }, null, 2);
              } else if (originalName === "createNote") {
                if (!doc) throw new Error("Process document context not loaded or slug is missing.");
                const id = `n-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`;
                const note = buildNote(
                  { author: args.author, text: args.content, type: args.type, replyTo: args.replyTo },
                  { id, ts: new Date().toISOString() }
                );
                appendNote(doc, args.elementId, note);
                atomicWriteFileSync(processFilePath, JSON.stringify(doc, null, 2) + "\n");
                resultText = JSON.stringify({ ok: true, note }, null, 2);
              } else if (originalName === "resolveNotes") {
                if (!doc) throw new Error("Process document context not loaded or slug is missing.");
                const noteIds = Array.isArray(args.noteIds) ? args.noteIds : [];
                const res = resolveNotesInDoc(doc, noteIds, args.resolvedBy, new Date().toISOString().slice(0, 10));
                atomicWriteFileSync(processFilePath, JSON.stringify(doc, null, 2) + "\n");
                resultText = JSON.stringify({ ok: true, ...res }, null, 2);
              } else if (originalName === "setApproval") {
                if (!this.slug) throw new Error("Process document context not loaded or slug is missing.");
                const patch = buildApprovalPatch(args.status, args.approver, new Date().toISOString().slice(0, 10));
                const res = await updateElement(this.slug, args.id, patch);
                if (!res.ok) {
                  resultText = `Error: ${res.error}`;
                } else {
                  resultText = JSON.stringify({ ok: true, id: args.id, approval: args.status }, null, 2);
                }
              } else if (originalName === "buildQueue") {
                if (!doc || !this.slug) throw new Error("Process document context not loaded or slug is missing.");
                const queue = buildFoundationalQueue(doc);
                const rs = newReviewState(this.slug, queue, new Date().toISOString());
                writeRuntime(this.slug, { reviewState: rs });
                resultText = JSON.stringify(foundationalStatus(rs), null, 2);
              } else if (originalName === "startSession") {
                if (!this.slug) throw new Error("Process document context not loaded or slug is missing.");
                const qs = newReviewState(this.slug, QER_STEPS, new Date().toISOString());
                writeRuntime(this.slug, { qerState: qs });
                resultText = JSON.stringify(qerStatus(qs), null, 2);
              } else if (originalName === "getSessionStatus") {
                if (!this.slug) throw new Error("Process document context not loaded or slug is missing.");
                const rt = getRuntime(this.slug);
                resultText = JSON.stringify(
                  args.kind === "qer" ? qerStatus(rt.qerState) : foundationalStatus(rt.reviewState),
                  null,
                  2
                );
              } else if (originalName === "advanceSession") {
                if (!this.slug) throw new Error("Process document context not loaded or slug is missing.");
                const rt = getRuntime(this.slug);
                const now = new Date().toISOString();
                if (args.kind === "qer") {
                  if (!rt.qerState) throw new Error("No qer session to advance — call startSession first.");
                  const next = advance(rt.qerState, now);
                  writeRuntime(this.slug, { qerState: next });
                  resultText = JSON.stringify(qerStatus(next), null, 2);
                } else {
                  if (!rt.reviewState) throw new Error("No foundational run to advance — call buildQueue first.");
                  const next = advance(rt.reviewState, now);
                  writeRuntime(this.slug, { reviewState: next });
                  resultText = JSON.stringify(foundationalStatus(next), null, 2);
                }
              } else {
                throw new Error(`Unsupported tool: ${originalName}`);
              }
            } catch (err: any) {
              console.error(`[gemini-worker] Tool execution failed: ${originalName}`, err);
              resultText = `Error executing tool: ${err.message}`;
            }

            const hasError = resultText.startsWith("Error:") || resultText.startsWith("Error executing tool:");
            appendToCentralLog(
              this.sessionId || "unknown",
              this.slug,
              hasError ? "Error" : "System",
              `Tool Response (${originalName}):\n${resultText}`
            );

            userParts.push({
              functionResponse: {
                name: originalName,
                response: { result: resultText },
                id: functionCallParts[idx]?.functionCall?.id || (call as any).id
              }
            });
          }

          // 3. Yield tool resolutions to complete the UI chips
          yield {
            type: "user",
            message: {
              content: calls.map((c, idx) => ({
                type: "tool_result",
                tool_use_id: `call_${turns}_${idx}`
              }))
            }
          };

          // 4. Record tool calls and responses into conversation history, then loop back
          const modelParts = response.candidates?.[0]?.content?.parts || calls.map(c => ({ functionCall: c }));
          this.history.push({ role: "model", parts: modelParts });
          this.history.push({ role: "user", parts: userParts });

        } else {
          // No more function calls: this is the final answer
          const text = response.text || "";

          this.history.push({
            role: "model",
            parts: [{ text }],
          });

          appendToCentralLog(this.sessionId || "unknown", this.slug, "Model", `Reply:\n${text}`);

          // Yield stream_event deltas so the client prints the text smoothly
          yield {
            type: "stream_event",
            event: {
              type: "content_block_delta",
              delta: {
                type: "text_delta",
                text: text,
              },
            },
          };

          // Yield the final result
          yield {
            type: "result",
            result: text,
            session_id: this.sessionId,
          };

          // Save history log to a debug file in the process directory
          if (this.slug && this.sessionId) {
            try {
              const debugDir = path.join(process.cwd(), "wiki", "processes", this.slug);
              if (!fs.existsSync(debugDir)) fs.mkdirSync(debugDir, { recursive: true });
              const debugFilePath = path.join(debugDir, `session-${this.sessionId}.debug.json`);
              
              // Clean history of thought signatures
              const cleanHistory = this.history.map(turn => {
                if (!turn || !Array.isArray(turn.parts)) return turn;
                return {
                  ...turn,
                  parts: turn.parts.map((p: any) => {
                    const copy = { ...p };
                    delete copy.thoughtSignature;
                    return copy;
                  })
                };
              });

              fs.writeFileSync(debugFilePath, JSON.stringify({
                activeSkill: this.activeSkill,
                activeTools: activeTools.map(t => ({ name: t.name, description: t.description, parameters: t.parameters })),
                systemInstruction,
                history: cleanHistory,
              }, null, 2), "utf8");
            } catch (err) {
              console.error("Failed to write session debug file:", err);
            }
          }

          loopActive = false;
        }
      }

      if (loopActive) {
        throw new Error(`The assistant exceeded the maximum allowed research turns (${MAX_TURNS}) for a single response.`);
      }
    } catch (e: any) {
      console.error("[gemini-worker] Error in runTurn:", e);
      appendToCentralLog(this.sessionId || "unknown", this.slug, "Error", `Turn Failure: ${e.message}`);
      yield {
        type: "error",
        error: e instanceof Error ? e.message : "The Gemini assistant turn failed.",
        session_id: this.sessionId,
      };
    } finally {
      this.busy = false;
      this.lastUsed = Date.now();
    }
  }

  dispose(): void {
    this.alive = false;
    this.history = [];
  }
}
