/**
 * Wry one-liners shown while a long chat turn waits.
 *
 * Each entry is the *second sentence* of:
 *
 *   "You've been waiting N minutes. [LINE]"
 *
 * Every line must therefore link back to the wait — either by
 * COMPARING the elapsed time to a banking thing that takes much
 * longer ("Still faster than getting Legal to commit to an SLA")
 * or by JUSTIFYING the wait with a quality outcome it buys ("Worth
 * it — higher provenance than the average compliance memo").
 *
 * Tone: dry, banker-aware, never mean. Lines that don't acknowledge
 * the wait or don't anchor in time-or-quality belong somewhere else.
 */
export const PERSPECTIVE_LINES: readonly string[] = [
  // --- TIME: the wait is reasonable because real-world X takes longer (1–110) ---
  "Still faster than getting Legal to commit to an SLA.",
  "Quicker than the IT change advisory's next Thursday.",
  "Sooner than the next ECB inspection.",
  "Less time than the Q4 close takes per region.",
  "A fraction of what the merger integration took.",
  "Faster than Procurement signs off on a new SaaS contract.",
  "Quicker than your last KYC refresh.",
  "Less time than month-end close. (Always.)",
  "Faster than the morning P&L sign-off cycle.",
  "Sooner than the model validation team's calendar opens.",
  "Quicker than the four-eyes second login on a Monday.",
  "Faster than getting Tax to agree on the memo length.",
  "Sooner than the annual policy review concludes.",
  "Quicker than the strategy off-site agrees on its agenda.",
  "Faster than the IT priority queue rotates.",
  "Sooner than the next change-window opens.",
  "Quicker than rendering the 47-slide quarterly deck.",
  "Faster than convincing Risk to update the appetite statement.",
  "Sooner than the model risk committee schedules a hearing.",
  "Well inside the 30-day subject access response window.",
  "Well under the 48-hour first-line escalation clock.",
  "Inside the 24-hour regulatory breach notification window.",
  "Quicker than the 14-day audit confirmation letter comes back.",
  "Faster than the 90-day remediation-plan close-out.",
  "Sooner than the next bank holiday.",
  "Quicker than the lift between floors when someone holds it.",
  "Faster than the resolvability assessment's next biennial cycle.",
  "A fraction of ICAAP's five-month submission window.",
  "Quicker than the EBA publishes its next guideline.",
  "Faster than the BCBS finishes consulting on a paper.",
  "Sooner than DORA Article 28 is interpreted by industry.",
  "Quicker than the FATF mutual evaluation cycle.",
  "Faster than the IRB model approval lands.",
  "Sooner than the nostro break from October finally reconciles.",
  "Quicker than your last all-hands meeting overran by.",
  "Faster than the working group reaches \"alignment.\"",
  "Sooner than the steering committee agrees on a meeting time.",
  "Quicker than the change-freeze ends in January.",
  "Faster than year-end close per legal entity.",
  "Sooner than the new-product approval forum's next agenda.",
  "Well inside the audit response window on a Cat-A finding.",
  "Faster than the auditor's clarification request gets answered.",
  "Sooner than the data lineage team finishes mapping a single field.",
  "Quicker than the data governance forum approves a metadata change.",
  "Faster than the new joiner's first KYC sign-off.",
  "Sooner than the badge access renewal cycle.",
  "Quicker than the SEPA cut-off window closes.",
  "Faster than the TARGET2 closing time.",
  "Sooner than CHAPS shuts at 17:40.",
  "Quicker than Fedwire closes at 18:00 EST.",
  "Faster than the DTCC overnight clear.",
  "Sooner than Euroclear's settlement window.",
  "Quicker than your morning espresso pulls through.",
  "Faster than a six-minute hard-boiled egg. (Take or leave.)",
  "Sooner than the S-Bahn from the airport arrives.",
  "Quicker than the canteen serves the schnitzel.",
  "Faster than the IT helpdesk's 5-day SLA.",
  "Sooner than the expense reimbursement cycle.",
  "Quicker than the procurement cycle for new software.",
  "Faster than rendering the strategy deck's appendix.",
  "Sooner than the Risk RAS workshop concludes.",
  "Quicker than the audit walkthrough takes per process.",
  "Faster than the policy committee meets again.",
  "Sooner than the FATF grey list next refreshes.",
  "Quicker than the next OFAC publication.",
  "Faster than the EBA Q&A inbox processes a question.",
  "Sooner than the corporate-portal session times out.",
  "Quicker than the Teams call's first seven minutes of introductions.",
  "Faster than the last five minutes of any meeting reaffirming the topic.",
  "Sooner than the minutes are circulated. (If at all.)",
  "Quicker than the Q4 board agenda gets decided in Q2.",
  "Faster than the leadership team agrees on a single OKR.",
  "Sooner than the strategy refresh cycle.",
  "A fraction of the planning cycle from August to November.",
  "Faster than the change-the-bank programme reports.",
  "Sooner than the workstream lead returns from holiday.",
  "Quicker than the model committee reviews a validation report.",
  "Faster than the credit committee adjudicates a borderline file.",
  "Sooner than a new corporate client gets their first portal login.",
  "Quicker than the new-product approval cycle (12 to 16 weeks).",
  "Faster than the IRB model's annual review.",
  "Sooner than the next stress-test scenario is finalised.",
  "Quicker than the recovery plan refresh cycle.",
  "Faster than ICAAP and ILAAP combined.",
  "Sooner than the regulator's next 60-day consultation closes.",
  "Quicker than the audit committee schedules its next read-out.",
  "Faster than the conduct dashboard refreshes.",
  "Sooner than the next conduct training module loads.",
  "Quicker than SharePoint finishes indexing a workspace.",
  "Faster than the database connection pool refreshes.",
  "Sooner than the VPN reconnects after lunch.",
  "Quicker than the printer on floor 12 finishes one page.",
  "Faster than the badge desk replaces a lost lanyard.",
  "Sooner than the deputy reads the policy memo.",
  "Quicker than the next German bank holiday.",
  "Faster than the half-year reporting deadline.",
  "Sooner than the year-end reporting deadline.",
  "Quicker than the model validation pre-read circulates.",
  "Faster than the post-trade reconciliation team flags a break.",
  "Sooner than the operational risk loss event is logged.",
  "Inside the 5-day near-miss reporting window.",
  "Inside the 4-hour material-event notification clock.",
  "Faster than a SOX walkthrough.",
  "Sooner than the next workshop about workshops.",
  "Quicker than a board paper goes through six drafts.",
  "Faster than the operations manual gets a single rewrite.",
  "Sooner than the corporate template's font is reviewed.",
  "Quicker than a legal opinion is escalated. (Twice.)",
  "Faster than the credit officer reaches their lunchtime.",
  "Sooner than the front-office desk's coffee round.",
  "Quicker than the regulator's 30-day RFI clock.",
  "Faster than the conformance script runs over the legacy product catalogue.",

  // --- QUALITY: the wait is justified because it buys X better than Y (111–185) ---
  "Worth it — we'd rather it be better than the QA scores on our last KYC refresh.",
  "Slow on purpose — to be better-sourced than the typical board pre-read.",
  "The wait buys you more provenance-stamping than the average compliance memo.",
  "Slow because we wanted stricter conformance than the front-office spreadsheet template.",
  "Worth it — higher fidelity than the legacy operations manual.",
  "Slow because we wanted it better cross-referenced than the audit response we filed in Q1.",
  "Worth it — more structured than the email chain that triggered this work.",
  "Slow because the output deserves a better filename than \"Final_v3_FINAL_actually_use_this.xlsx\".",
  "Worth it — more legible than the auditor's hand-written marginalia.",
  "The wait gives you cleaner provenance than the average MRA response.",
  "Slow because we wanted it better-versioned than the SharePoint folder it replaces.",
  "Worth it — more auditable than the chat thread between Legal and Ops.",
  "The wait buys higher provenance per word than the EBA Q&A inbox.",
  "Slow on purpose — better governed than the data dictionary on the shared drive.",
  "Worth it — more elicited than the last RACI matrix the team circulated.",
  "The wait buys higher confidence per claim than the model documentation pack.",
  "Slow because we wanted it more verifiable than the typical end-of-day MIS report.",
  "Worth it — better tagged than the operational risk taxonomy.",
  "The wait buys more cross-references than the Basel-mapped policy library.",
  "Slow because we wanted action items better-defined than the average MRA item.",
  "Worth it — more closely sourced than the typical executive summary.",
  "Slow on purpose — better controlled than the consultation paper draft floor.",
  "The wait gives you higher integrity than the BCBS-239 lineage diagram.",
  "Worth it — more disciplined than the front-office's MIS pivot.",
  "Slow because we wanted it more auditable than the last sanctions-hit investigation log.",
  "The wait buys a higher data-quality score than the customer master file.",
  "Worth it — better-stamped than the audit response we wrote in March.",
  "Slow because we wanted it more schema-aligned than the IFRS9 model documentation.",
  "The wait gives you cleaner cross-references than the regulator's own Q&A archive.",
  "Worth it — more confidence-rated than the typical risk-and-control matrix.",
  "Slow because we wanted it better-versioned than the global product catalogue.",
  "The wait buys higher provenance than the typical executive sponsor's email.",
  "Worth it — more structured than the off-cycle product approval memo.",
  "Slow because we wanted it better-classified than the typical board pre-read.",
  "The wait gives you higher consistency than the front-office's morning P&L commentary.",
  "Worth it — more schema-faithful than the typical product control reconciliation.",
  "Slow on purpose — better-tagged than the operational risk loss database.",
  "The wait buys higher signal-to-noise than the weekly all-hands deck.",
  "Worth it — more reproducible than the typical Excel-based stress test.",
  "Slow because we wanted it better cross-linked than the regulator's own framework index.",
  "The wait gives you higher fidelity than the manual screenshot trail in the audit pack.",
  "Worth it — more structured than the chat-based handover from night-shift.",
  "Slow because we wanted better lineage than the dotted-line ownership chart.",
  "The wait buys higher schema discipline than the Excel-based product taxonomy.",
  "Worth it — more uniform than the desk-by-desk reporting template.",
  "Slow because we wanted better evidence than the average control-effectiveness rating.",
  "The wait gives you more consistency than the lint findings we keep deferring.",
  "Worth it — higher rigour than the periodic re-attestation cycle.",
  "Slow on purpose — better traceability than the IT asset register.",
  "The wait buys more structure than the post-incident review template.",
  "Worth it — better-attributed than the audit's chronology of events.",
  "Slow because we wanted it higher-confidence than the typical risk officer's quarterly write-up.",
  "The wait gives you more schema-compliance than the regulator's own templates.",
  "Worth it — better-evidenced than the typical product committee minute.",
  "Slow because we wanted higher precision than the legacy operational manual.",
  "The wait buys more verifiability than the operational risk control library.",
  "Worth it — better-cited than the strategy team's annual narrative.",
  "Slow on purpose — higher quality than the average Q3 audit response.",
  "The wait gives you more structure than the operational risk loss database.",
  "Worth it — better-elicited than the typical pain-point captured in Slack.",
  "Slow because we wanted higher coverage than the operations manual on this process.",
  "The wait buys more uniformity than the email-based KYC follow-up trail.",
  "Worth it — better-defined than the dotted-line ownership chart in HR.",
  "Slow because we wanted higher fidelity than the operations manual section on this process.",
  "The wait gives you more cross-references than the audit committee's read-pack.",
  "Worth it — better-cited than the regulator's last clarification reply.",
  "Slow on purpose — more auditable than the legacy escalation matrix.",
  "The wait buys higher provenance per element than the customer master.",
  "Worth it — better cross-links than the policy library.",
  "Slow because we wanted it more schema-faithful than the corporate product catalogue.",
  "The wait gives you higher integrity than the morning reconciliation report.",
  "Worth it — more confidence-stamped than the model risk report.",
  "Slow because we wanted it better-evidenced than last quarter's audit response.",
  "The wait buys higher coverage than the IT asset inventory.",
  "Worth it — more structured than the off-shore handover deck.",
  "Slow on purpose — higher consistency than the all-hands Q&A summary.",

  // --- HYBRID: yes, slow — but faster than X AND better than Y (186–200) ---
  "Slow, sure — still faster than a SOX walkthrough, and more reproducible.",
  "Slow, sure — still quicker than a model validation review, and better evidenced.",
  "Slow, sure — still sooner than the next policy refresh, and more cross-referenced.",
  "Slow, sure — still less time than a stress-test design, and more schema-compliant.",
  "Slow, sure — still faster than the IRB approval, with better provenance per claim.",
  "Slow, sure — still quicker than the recovery-plan refresh, with higher schema discipline.",
  "Slow, sure — still sooner than the next ICAAP cycle, and better cross-referenced.",
  "Slow, sure — still less time than an audit walkthrough, and better stamped.",
  "Slow, sure — still faster than the data-governance forum, and more auditable.",
  "Slow, sure — still quicker than the regulator's clarification reply, and better cited.",
  "Slow, sure — still sooner than the recovery plan re-runs, and higher fidelity.",
  "Slow, sure — still less time than the model risk officer's review, and more verifiable.",
  "Slow, sure — still faster than year-end close, with more confidence-stamped output.",
  "Slow, sure — still quicker than the change advisory's next slot, and better-tagged.",
  "Slow, sure — still sooner than the next strategy refresh, and more reproducible.",
];

/** Random pick from the perspective pool. Empty string if the pool is empty. */
export function pickPerspective(): string {
  if (PERSPECTIVE_LINES.length === 0) return "";
  const i = Math.floor(Math.random() * PERSPECTIVE_LINES.length);
  return PERSPECTIVE_LINES[i] ?? "";
}
