// Schema drift-guard (R-track "schema consolidation") — run: npm test
//
// The project keeps the process schema in two representations:
//   - schema/process-schema.json            — the custom app schema (source of truth)
//   - src/lib/schema/process-schema.json     — the Draft-07 JSON Schema (auto-generated)
//
// This test ensures that the file on disk (src/lib/schema/process-schema.json) is
// 100% up-to-date and matches the output generated by generateSchema. If it fails,
// run the generator script to update the on-disk schema.
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { generateSchema } from "./generate.ts";

const root = process.cwd();
const custom = JSON.parse(
  readFileSync(join(root, "schema", "process-schema.json"), "utf8"),
);
const onDisk = JSON.parse(
  readFileSync(join(root, "src", "lib", "schema", "process-schema.json"), "utf8"),
);

test("schema drift-guard: on-disk JSON schema matches the generated output", () => {
  const generated = generateSchema(custom);
  
  try {
    assert.deepEqual(onDisk, generated);
  } catch (err: any) {
    assert.fail(
      "The on-disk JSON Schema (src/lib/schema/process-schema.json) does not match the output generated from the custom schema (schema/process-schema.json).\n" +
      "Please run 'npm run generate-schema' (or 'node --experimental-strip-types scripts/generate-json-schema.ts') to update it."
    );
  }
});

